### ISSUE TITLE
Update Dataset in place instead of creating new directory for each new version

### ISSUE THREAD

**Issue by imincik** [linz/geostore#1050]
Update Dataset on place instead of current design which creates new directory for each new version.

### User Story

So that we can manage the cost of versioning, as a product owner, I want to use in place S3 object versioning so that we can develop partial version updates.

#### Acceptance Criteria

- [ ] When a user submits a new version, then files are stored in the dataset top level directory and files are overwritten (S3 Object Versions created) - estimate 5

#### Tasks

- [x] Change tests to see what breaks
- [ ] Fix things until all the tests pass again
- [ ] Get rid of unreachable code

#### Definition of Ready

- [ ] This story is **ready** to work on
  - [ ] Independent (story is independent of all other tasks)
  - [ ] Negotiable (team can decide how to design and implement)
  - [ ] Valuable (from a user perspective)
  - [ ] Estimate value applied (agreed by team)
  - [ ] Small (so as to fit within an iteration)
  - [ ] Testable (in principle, even if there isn't a test for it yet)
  - [ ] Environments are ready to meet definition of done
  - [ ] Resources required to implement will be ready
  - [ ] Everyone understands and agrees with the tasks to complete the story
  - [ ] Release value (e.g. Iteration 3) applied
  - [ ] Sprint value (e.g. Aug 1 - Aug 15) applied

#### Definition of Done

- [ ] This story is **done**:
  - [ ] Acceptance criteria completed
  - [ ] Automated tests are passing
  - [ ] Code is peer reviewed and pushed to master
  - [ ] Deployed successfully to test environment
  - [ ] Checked against [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
  - [ ] Relevant new tasks are added to backlog and communicated to the team
  - [ ] Important decisions recorded in the issue ticket
  - [ ] Readme/Changelog/Diagrams are updated
  - [ ] Product Owner has approved acceptance criteria as complete
  - [ ] Meets non-functional requirements:
    - [ ] Scalability (data): Can scale to 300TB of data and 100,000,000 files and ability to
          increase 10% every year
    - [ ] Scability (users): Can scale to 100 concurrent users
    - [ ] Cost: Data can be stored at < 0.5 NZD per GB per year
    - [ ] Performance: A large dataset (500 GB and 50,000 files - e.g. Akl aerial imagery) can be
          validated, imported and stored within 24 hours
    - [ ] Accessibility: Can be used from LINZ networks and the public internet
    - [ ] Availability: System available 24 hours a day and 7 days a week, this does not include
          maintenance windows < 4 hours and does not include operational support
    - [ ] Recoverability: RPO of fully imported datasets < 4 hours, RTO of a single 3 TB dataset <
          12 hours

**Comment by billgeo** [comment]
Discussion with Victor

- Could be ~ 20 tests to change

**Comment by billgeo** [comment]
@MitchellPaff has done some test changes, but might have found a bug in pystac or some other issue.
Be good to pair on this and chug through it.

**Comment by billgeo** [comment]
Hey @MitchellPaff I tested this and found one issue

We now no longer have a top level catalog and no link to the parent in the dataset collection.json (presumably because tehre is not catalog.json in the top level.

**Comment by billgeo** [comment]
Tested in nonprod accoutn and working well. Thanks @MitchellPaff .
