### ISSUE TITLE
Speed up `cdk deploy`

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#1061]
### Enabler

So that we can work faster, we want to make sure CDK deployments take a reasonably short amount of time

#### Acceptance Criteria

- [ ] CDK deployments are 'faster', or major bottlenecks are investigated and current speed is accepted
- [ ] ...

#### Tasks

- [ ] Check whether we can speed up Python package installs. Downloading ("collecting") the packages takes only 4s, and it looks like all the individual packages install really quickly. We could use a Nix shell with the "linz" Cachix cache.
- [ ] Figure out what CDK is doing when not printing anything for long stretches of time. Maybe we need to force unbuffered output from CDK to get more accurate timings.
- [ ] Check for any common ways to speed up CDK prep/deployment/destroy.
- [ ] Check whether it's possible to have a "post-pipeline" action in GitHub which cleans up the CI environment *eventually* but not as part of the build job, so that we can ignore the last >5m.
- [ ] Check how to cache Docker builds between jobs.
- [ ] Can we use a smaller Docker base image?
- [ ] Can we deploy a raw Python package to Lambda?

#### Additional context

Timing information from [an arbitrary job](https://github.com/linz/geostore/runs/3864857465?check_suite_focus=true) with long runtimes **highlighted**:

1. Spends 11 seconds doing setup
1. Downloads repos for 7s
2. Sets up Node.js for 3s
2. Fetches Node.js cache for 4s
3. Sets up Python for 8s
4. Fetches Python cache for 1s
5. Installs Python packages for **1m37s**
6. Configures AWS credentials for 3s
7. CDK deploy runs for **20m43s**
   1. CDK does initial setup without printing any useful diagnostics for 57s
   2. Builds `amazon/aws-sam-cli-build-image-python3.8` Docker image for **5m5s**
   3. Bundles assets for <1s
   4. Spends **4m52s** doing nothing visible
   3. Builds the *same* container and gives it a different tag in <1s
   4. Publishes assets for **1m28s**
   5. Builds Lambda Ubuntu Docker container for **1m0s**
   6. Pushes to ECR for 13s
   7. Deploys for **7m7s**
1. Runs tests for **10m49s**
2. Generates coverage report for 2s
3. Destroys infrastructure for **5m19**
   1. Spends 50s doing nothing visible
   2. Builds Python Docker container for <1s
   3. Destroys infrastructure for **4m26s**
4. Cleans up for 7s

#### Definition of Ready

- [ ] This story is **ready** to work on
  - [ ] Negotiable (team can decide how to design and implement)
  - [ ] Valuable (from a user perspective)
  - [ ] Estimate value applied (agreed by team)
  - [ ] Small (so as to fit within an iteration)
  - [ ] Testable (in principle, even if there isn't a test for it yet)
  - [ ] Environments are ready to meet definition of done
  - [ ] Resources required to implement will be ready
  - [ ] Everyone understands and agrees with the tasks to complete the story
  - [ ] Release value (e.g. Iteration 3) applied
  - [ ] Sprint value (e.g. Aug 1 - Aug 15) applied

#### Definition of Done

- [ ] This story is **done**:
  - [ ] Acceptance criteria completed
  - [ ] Automated tests are passing
  - [ ] Code is peer reviewed and pushed to master
  - [ ] Deployed successfully to test environment
  - [ ] Checked against [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
  - [ ] Relevant new tasks are added to backlog and communicated to the team
  - [ ] Important decisions recorded in the issue ticket
  - [ ] Readme/Changelog/Diagrams are updated
  - [ ] Product Owner has approved acceptance criteria as complete
  - [ ] Meets non-functional requirements:
    - [ ] Scalability (data): Can scale to 300TB of data and 100,000,000 files and ability to
          increase 10% every year
    - [ ] Scability (users): Can scale to 100 concurrent users
    - [ ] Cost: Data can be stored at < 0.5 NZD per GB per year
    - [ ] Performance: A large dataset (500 GB and 50,000 files - e.g. Akl aerial imagery) can be
          validated, imported and stored within 24 hours
    - [ ] Accessibility: Can be used from LINZ networks and the public internet
    - [ ] Availability: System available 24 hours a day and 7 days a week, this does not include
          maintenance windows < 4 hours and does not include operational support
    - [ ] Recoverability: RPO of fully imported datasets < 4 hours, RTO of a single 3 TB dataset <
          12 hours

**Comment by billgeo** [comment]
Great to shave some time off here. Thanks @Jimlinz
