### ISSUE TITLE
Analyse hydro geodetic need for versioning

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#1070]
### Enabler

So that we can confirm the design and user stories for new versioning design, we want to understand their overall process and how the manage and access older versions of their dataset

#### Acceptance Criteria

- [ ] Understand their overall data management process including problems and paint points 
- [ ] Understand what a 'dataset' is for them
- [ ] Understand how and when they update datasets vs creating new datasets
- [ ] Understand at high level how other groups currently access old versions of data
- [ ] Understand how other groups want to access old version of data in the future
- [ ] Update #559 or create new stories (#1050 #1051 #1049) with design, tasks and estimates

#### Tasks

- [ ] Have a workshop with hydro and Geodetic about how the update and manage their data and what problems they have
- [ ] Include what new things would make their life easier/better
- [ ] Update the design
- [ ] Convert anaylsis into stories

#### Definition of Ready

- [ ] This story is **ready** to work on
  - [ ] Negotiable (team can decide how to design and implement)
  - [ ] Valuable (from a user perspective)
  - [ ] Estimate value applied (agreed by team)
  - [ ] Small (so as to fit within an iteration)
  - [ ] Testable (in principle, even if there isn't a test for it yet)
  - [ ] Environments are ready to meet definition of done
  - [ ] Resources required to implement will be ready
  - [ ] Everyone understands and agrees with the tasks to complete the story
  - [ ] Release value (e.g. Iteration 3) applied
  - [ ] Sprint value (e.g. Aug 1 - Aug 15) applied

#### Definition of Done

- [ ] This story is **done**:
  - [ ] Acceptance criteria completed
  - [ ] Automated tests are passing
  - [ ] Code is peer reviewed and pushed to master
  - [ ] Deployed successfully to test environment
  - [ ] Checked against [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
  - [ ] Relevant new tasks are added to backlog and communicated to the team
  - [ ] Important decisions recorded in the issue ticket
  - [ ] Readme/Changelog/Diagrams are updated
  - [ ] Product Owner has approved acceptance criteria as complete
  - [ ] Meets non-functional requirements:
    - [ ] Scalability (data): Can scale to 300TB of data and 100,000,000 files and ability to
          increase 10% every year
    - [ ] Scability (users): Can scale to 100 concurrent users
    - [ ] Cost: Data can be stored at < 0.5 NZD per GB per year
    - [ ] Performance: A large dataset (500 GB and 50,000 files - e.g. Akl aerial imagery) can be
          validated, imported and stored within 24 hours
    - [ ] Accessibility: Can be used from LINZ networks and the public internet
    - [ ] Availability: System available 24 hours a day and 7 days a week, this does not include
          maintenance windows < 4 hours and does not include operational support
    - [ ] Recoverability: RPO of fully imported datasets < 4 hours, RTO of a single 3 TB dataset <
          12 hours

**Comment by billgeo** [comment]
Will do this as and when needed.
