### ISSUE TITLE
Setup Geostore in LINZ Central Logging and Analytics system

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#1112]
### User Story

So that I can access information about the system (e.g. with Elasticsearch and Kibana), as a Data Analyst, Developer or Administrator, I want logs sent to LINZ central logging system.

#### Acceptance Criteria

- [x] Given the system is deployed to the production environment, when any event happens, then log messages are sent to the LINZ central logging system
- [x] Given I am an authenticated Admin, I can view and analyse all logs
- [ ] Given I am an authenicated Data Maintainer, when an error happens during a data maintenance function, then I am provided a link to LINZ central logging with all the relevant logs

#### Additional context
LINZ Central logging is in undergoing upgrade which will result in logging process and setup simplification. In [Logging documentation](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=83649508), top diagram is showing new state and lower one the old one.

* [aws-log-config](https://github.com/linz/aws-log-config) will be used to configure log shipping. 
* aws-log-config depends on [linzjs/cdk-elastic-shipper](https://github.com/linz/elasticsearch-shipper)
* [ept-central-applogs](https://github.com/linz/ept-central-applogs) is used for deployment of whole LINZ Central Logging solution

In new version of LINZ Centralized Logging all logs from product AWS account should be automatically imported to LINZ Centralized Logging system based on aws-log-config configuration (see [basemaps config](https://github.com/linz/aws-log-config/blob/master/config/basemaps.json) as example).

New LINZ Centralized Logging version is not ready yet (needs few weeks to be finished and to populate aws-log-config with configuration for all products). 

Kibana needs space created, it is not automatic
Slack messages are configured by ElasticSearch configuration (see: https://github.com/linz/basemaps-team/blob/master/config/elasticsearch/watch.aws.AssumeRoleWithSAML.json)

#### Tasks

- [ ] TBD

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [x] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Hi @MitchellPaff I added a 5 estimate to this. Can you please update if there's a better number?

**Comment by billgeo** [comment]
Closing, Will open up another issue to tidy up the message formatting and version control the Kibana config
