### ISSUE TITLE
Geostore CLI nice-to-haves

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#1146]
### User Story

So that the Geostore CLI is as useful as possible, as a dataset maintainer, I want to it to have standard bells and whistles.

#### Acceptance Criteria
- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]
- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]

#### Tasks

- [ ] Implement `--version` flag to print package version
- [ ] Implement `--color=never|auto|always` flag to override default behaviour?
- [ ] Implement `--verbose` flag to print more human readable but non-programmable output?

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Added some ideas to this @l0b0. Let's discuss these though and come up with an order of priority.
