### ISSUE TITLE
Logging: Improve json content formatting in Kibana/Elastic

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#1169]
### User Story

So that logging is as usable as possible, as a , I want logging content json messages formatted as key:value so I can search and filter on them easily.

#### Acceptance Criteria

- [x] Given a lambda log is generated, when it is shipped to elastic search, then the main log message json is formatted as key:value pairs in Kibana, so the are display as properties and values and can be queried/fitlered etc.

#### Tasks

- [x] Make changes to format the log messages
- [x] Add Kibana config to Github

#### Definition of Ready

- [ ] This story is **ready** to work on
  - [ ] Independent (story is independent of all other tasks)
  - [ ] Negotiable (team can decide how to design and implement)
  - [ ] Valuable (from a user perspective)
  - [ ] Estimate value applied (agreed by team)
  - [ ] Small (so as to fit within an iteration)
  - [ ] Testable (in principle, even if there isn't a test for it yet)
  - [ ] Environments are ready to meet definition of done
  - [ ] Resources required to implement will be ready
  - [ ] Everyone understands and agrees with the tasks to complete the story
  - [ ] Release value (e.g. Iteration 3) applied
  - [ ] Sprint value (e.g. Aug 1 - Aug 15) applied

#### Definition of Done

- [x] This story is **done**:
  - [ ] Acceptance criteria completed
  - [ ] Automated tests are passing
  - [ ] Code is peer reviewed and pushed to master
  - [ ] Deployed successfully to test environment
  - [ ] Checked against [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
  - [ ] Relevant new tasks are added to backlog and communicated to the team
  - [ ] Important decisions recorded in the issue ticket
  - [ ] Readme/Changelog/Diagrams are updated
  - [ ] Product Owner has approved acceptance criteria as complete
  - [ ] Meets non-functional requirements:
    - [ ] Scalability (data): Can scale to 300TB of data and 100,000,000 files and ability to
          increase 10% every year
    - [ ] Scability (users): Can scale to 100 concurrent users
    - [ ] Cost: Data can be stored at < 0.5 NZD per GB per year
    - [ ] Performance: A large dataset (500 GB and 50,000 files - e.g. Akl aerial imagery) can be
          validated, imported and stored within 24 hours
    - [ ] Accessibility: Can be used from LINZ networks and the public internet
    - [ ] Availability: System available 24 hours a day and 7 days a week, this does not include
          maintenance windows < 4 hours and does not include operational support
    - [ ] Recoverability: RPO of fully imported datasets < 4 hours, RTO of a single 3 TB dataset <
          12 hours

**Comment by MitchellPaff** [comment]
log message can be viewed in kibana [here.](https://li.kb.ap-southeast-2.aws.found.io:9243/s/datalake/app/discover#/doc/f0360980-3d1a-11ec-9e27-d7f8ac91af76/geostore-nonprod-2021-11-04?id=ZfmcC30BFrDxld6olQTn)
