### ISSUE TITLE
Manage deleted files in dataset new version

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#1224]
### User Story

So that files that have been removed from a dataset don't appear in the dataset, as a data maintainer, I want files that I have removed from my dataset to not appear in the s3 directory for the dataset (it will still appear in the S3 file versions)

#### Acceptance Criteria

- [ ] Given a new version has been submitted, when files are missing (no longer referenced in any of the metadata) from the dataset (i.e. deleted), then a 'delete marker' is applied to the file in s3

#### Additional context

Should apply to assets and metadata.

#### Tasks

- [x] Record which files are being updated
- [x] Cleanup on failure
- [x] Mark files for deletion at the end of the process

#### Definition of Ready

- [ ] This story is **ready** to work on
  - [ ] Independent (story is independent of all other tasks)
  - [ ] Negotiable (team can decide how to design and implement)
  - [ ] Valuable (from a user perspective)
  - [ ] Estimate value applied (agreed by team)
  - [ ] Small (so as to fit within an iteration)
  - [ ] Testable (in principle, even if there isn't a test for it yet)
  - [ ] Environments are ready to meet definition of done
  - [ ] Resources required to implement will be ready
  - [ ] Everyone understands and agrees with the tasks to complete the story
  - [ ] Release value (e.g. Iteration 3) applied
  - [ ] Sprint value (e.g. Aug 1 - Aug 15) applied

#### Definition of Done

- [ ] This story is **done**:
  - [ ] Acceptance criteria completed
  - [ ] Automated tests are passing
  - [ ] Code is peer reviewed and pushed to master
  - [ ] Deployed successfully to test environment
  - [ ] Checked against [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
  - [ ] Relevant new tasks are added to backlog and communicated to the team
  - [ ] Important decisions recorded in the issue ticket
  - [ ] Readme/Changelog/Diagrams are updated
  - [ ] Product Owner has approved acceptance criteria as complete
  - [ ] Meets non-functional requirements:
    - [ ] Scalability (data): Can scale to 300TB of data and 100,000,000 files and ability to
          increase 10% every year
    - [ ] Scability (users): Can scale to 100 concurrent users
    - [ ] Cost: Data can be stored at < 0.5 NZD per GB per year
    - [ ] Performance: A large dataset (500 GB and 50,000 files - e.g. Akl aerial imagery) can be
          validated, imported and stored within 24 hours
    - [ ] Accessibility: Can be used from LINZ networks and the public internet
    - [ ] Availability: System available 24 hours a day and 7 days a week, this does not include
          maintenance windows < 4 hours and does not include operational support
    - [ ] Recoverability: RPO of fully imported datasets < 4 hours, RTO of a single 3 TB dataset <
          12 hours

**Comment by billgeo** [comment]
Did a really simple test with a dataset with two assets, and then did a delete on one asset and a update on the other and all the versions and delete markers are as I'd expect. Thanks @MitchellPaff 

```
Bills-MacBook-Pro:geostore_test03 bill$ aws s3api list-object-versions --bucket nonprod-linz-geostore --prefix Bill-test-delete-files
{
    "Versions": [
        {
            "ETag": "\"8cad767ba9a7716824da3800735a27de\"",
            "Size": 2248,
            "StorageClass": "STANDARD",
            "Key": "Bill-test-delete-files/collection.json",
            "VersionId": "Tfe6_uaRQsmplkIZPdtSwlNC_qiilyAQ",
            "IsLatest": true,
            "LastModified": "2022-07-01T00:19:33+00:00",
            "Owner": {
                "DisplayName": "linz-aws-root-datalake-nonprod",
                "ID": "6489c293f4a0cf9fc1d7bd73a8e0fa39194cc645a4d277cd74bbe71183297814"
            }
        },
        {
            "ETag": "\"ad628694f8265fb39648acf72456145c\"",
            "Size": 2492,
            "StorageClass": "STANDARD",
            "Key": "Bill-test-delete-files/collection.json",
            "VersionId": "7Qh7iLxO_jfeBBLK8FJqV.h43nZjUXWW",
            "IsLatest": false,
            "LastModified": "2022-06-30T23:27:32+00:00",
            "Owner": {
                "DisplayName": "linz-aws-root-datalake-nonprod",
                "ID": "6489c293f4a0cf9fc1d7bd73a8e0fa39194cc645a4d277cd74bbe71183297814"
            }
        },
        {
            "ETag": "\"3161ae7fc12f286be38c7ab46cb41617\"",
            "Size": 27,
            "StorageClass": "STANDARD",
            "Key": "Bill-test-delete-files/test_file.txt",
            "VersionId": "oBqXbdupUvkZpXQINN0edwEEP118oXkO",
            "IsLatest": false,
            "LastModified": "2022-06-30T23:27:32+00:00",
            "Owner": {
                "DisplayName": "linz-aws-root-datalake-nonprod",
                "ID": "6489c293f4a0cf9fc1d7bd73a8e0fa39194cc645a4d277cd74bbe71183297814"
            }
        },
        {
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Key": "Bill-test-delete-files/test_file_02.txt",
            "VersionId": "pb1KwNyYLmYAFo5aY7mfY_yQZ1.frR0L",
            "IsLatest": true,
            "LastModified": "2022-07-01T00:19:32+00:00",
            "Owner": {
                "DisplayName": "linz-aws-root-datalake-nonprod",
                "ID": "6489c293f4a0cf9fc1d7bd73a8e0fa39194cc645a4d277cd74bbe71183297814"
            }
        },
        {
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Key": "Bill-test-delete-files/test_file_02.txt",
            "VersionId": "dVuy1aNMSh7zl21vlYfTSIfdw0R0Fm1J",
            "IsLatest": false,
            "LastModified": "2022-06-30T23:27:32+00:00",
            "Owner": {
                "DisplayName": "linz-aws-root-datalake-nonprod",
                "ID": "6489c293f4a0cf9fc1d7bd73a8e0fa39194cc645a4d277cd74bbe71183297814"
            }
        }
    ],
    "DeleteMarkers": [
        {
            "Owner": {
                "DisplayName": "linz-aws-root-datalake-nonprod",
                "ID": "6489c293f4a0cf9fc1d7bd73a8e0fa39194cc645a4d277cd74bbe71183297814"
            },
            "Key": "Bill-test-delete-files/test_file.txt",
            "VersionId": "T76ltW5ylKYA0URk6E4u8.DT5L..Ocjq",
            "IsLatest": true,
            "LastModified": "2022-07-01T00:20:16+00:00"
        }
    ]
}

```
