### ISSUE TITLE
Make sure we can run more than two pipelines simultaneously

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#1450]
### Enabler

So that we can get quick feedback, we want to make sure pipelines don't interfere with each other via AWS limits.

#### Acceptance Criteria

- [ ] At least six pipelines can run simultaneously

#### Additional context

From the logs:

> CREATE_FAILED        | AWS::CloudTrail::Trail           | api/cloudtrail (apicloudtrail31CA7546) Resource handler returned message: "Invalid request provided: User: *** already has 5 trails in ap-southeast-2. (Service: CloudTrail, Status Code: 400, Request ID: …, Extended Request ID: null)" (RequestToken: …, HandlerErrorCode: InvalidRequest)

That's why we should be able to run at least six simultaneously.

#### Tasks

- [x] Pull out separate logging stack
- [x] Deploy
- [x] Run at least one of the endpoints with `pytest tests/test_processing_stack.py::should_successfully_run_dataset_version_creation_process_with_single_asset`
- [x] Verify that the endpoint interaction was logged
- [x] Re-deploy to verify that it's idempotent

Ideas:

- Use the same CloudTrail trail for each CI pipeline. One way to do this is to put the CloudTrail stuff in a separate stack, but that means we [lose the direct connection to the endpoint Lambdas](https://stackoverflow.com/q/71462211/96588).
- Remove the CloudTrail trail from the Geostore completely
- Create the CloudTrail trail only in non-CI accounts

#### Definition of Ready

- [ ] This story is **ready** to work on
  - [ ] Negotiable (team can decide how to design and implement)
  - [ ] Valuable (from a user perspective)
  - [ ] Estimate value applied (agreed by team)
  - [ ] Small (so as to fit within an iteration)
  - [ ] Testable (in principle, even if there isn't a test for it yet)
  - [ ] Environments are ready to meet definition of done
  - [ ] Resources required to implement will be ready
  - [ ] Everyone understands and agrees with the tasks to complete the story
  - [ ] Release value (e.g. Iteration 3) applied
  - [ ] Sprint value (e.g. Aug 1 - Aug 15) applied

#### Definition of Done

- [ ] This story is **done**:
  - [ ] Acceptance criteria completed
  - [ ] Automated tests are passing
  - [ ] Code is peer reviewed and pushed to master
  - [ ] Deployed successfully to test environment
  - [ ] Checked against [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
  - [ ] Relevant new tasks are added to backlog and communicated to the team
  - [ ] Important decisions recorded in the issue ticket
  - [ ] Readme/Changelog/Diagrams are updated
  - [ ] Product Owner has approved acceptance criteria as complete
  - [ ] Meets non-functional requirements:
    - [ ] Scalability (data): Can scale to 300TB of data and 100,000,000 files and ability to
          increase 10% every year
    - [ ] Scability (users): Can scale to 100 concurrent users
    - [ ] Cost: Data can be stored at < 0.5 NZD per GB per year
    - [ ] Performance: A large dataset (500 GB and 50,000 files - e.g. Akl aerial imagery) can be
          validated, imported and stored within 24 hours
    - [ ] Accessibility: Can be used from LINZ networks and the public internet
    - [ ] Availability: System available 24 hours a day and 7 days a week, this does not include
          maintenance windows < 4 hours and does not include operational support
    - [ ] Recoverability: RPO of fully imported datasets < 4 hours, RTO of a single 3 TB dataset <
          12 hours

**Comment by l0b0** [comment]
We're still running into
> Invalid request provided: User: *** already has 5 trails in ap-southeast-2. (Service: CloudTrail, Status Code: 400, Request ID: 84159f81-135d-45f7-988c-6701ac420199, Extended Request ID: null)
when testing upgrades from current production, so we probably need to release to production to fix this properly.

**Comment by l0b0** [comment]
Closed in #1493.
