### ISSUE TITLE
Allow Topo Data Pipeline to assume role without AD authentication

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#1585]
### User Story

So that I can import data to the geostore from a pipeline or machine, as a LINZ/Topo developer, I want to authenticate from my AWS pipeline/account/process, instead of assuming a role that requires a user to be part of an AD group

Currently users assume the role `geostore-prod-api-users` which is connected to an AD group `A_AWS_LINZ_LI_Datalake_Maintainers`

#### Acceptance Criteria

- [ ] Given that I am logged in to the LINZ AWS org, when I invoke a Geostore lambda, then I am allowed to do so
- [ ] Given I am not logged in to the LINZ AWS org, when I invoke a Geostore lambda, then I am not allowed to do so

#### Additional context

Discussion with TDE team on 28/04/22:

1. They are building a CLI tool where the user has assumed an AD linked role already and can't assume another AD linked role in the same session
2. They may end up automating the entire process in the future, so there may be no user involved at all
3. They will be running their process from multiple accounts in the future at least 4 and probably more

Discussed some possible solutions:

1. Allow assuming the role from any LINZ AWS account
    a.  This would mean any LINZ dev or anyone with AWS access could overwrite existing data
    b. may want to add monitoring and/or prevention to catch actors that accidentally overwrite someone else's data
    c. may have to revisit this in the future if it becomes a problem
3. Allow assuming the role to a list of Topo accounts
    a. This could become unwieldly to manage if there is a large or constantly changing list of accounts that need to be redeployed every time 

#### Tasks

- [ ] Figure out how to test this
- [ ] Write a test that fails
- [ ] Make changes so that it passes

#### Definition of Ready

- [ ] This story is **ready** to work on
  - [ ] Independent (story is independent of all other tasks)
  - [ ] Negotiable (team can decide how to design and implement)
  - [ ] Valuable (from a user perspective)
  - [ ] Estimate value applied (agreed by team)
  - [ ] Small (so as to fit within an iteration)
  - [ ] Testable (in principle, even if there isn't a test for it yet)
  - [ ] Environments are ready to meet definition of done
  - [ ] Resources required to implement will be ready
  - [ ] Everyone understands and agrees with the tasks to complete the story
  - [ ] Release value (e.g. Iteration 3) applied
  - [ ] Sprint value (e.g. Aug 1 - Aug 15) applied

#### Definition of Done

- [ ] This story is **done**:
  - [ ] Acceptance criteria completed
  - [ ] Automated tests are passing
  - [ ] Code is peer reviewed and pushed to master
  - [ ] Deployed successfully to test environment
  - [ ] Checked against [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
  - [ ] Relevant new tasks are added to backlog and communicated to the team
  - [ ] Important decisions recorded in the issue ticket
  - [ ] Readme/Changelog/Diagrams are updated
  - [ ] Product Owner has approved acceptance criteria as complete
  - [ ] Meets non-functional requirements:
    - [ ] Scalability (data): Can scale to 300TB of data and 100,000,000 files and ability to
          increase 10% every year
    - [ ] Scability (users): Can scale to 100 concurrent users
    - [ ] Cost: Data can be stored at < 0.5 NZD per GB per year
    - [ ] Performance: A large dataset (500 GB and 50,000 files - e.g. Akl aerial imagery) can be
          validated, imported and stored within 24 hours
    - [ ] Accessibility: Can be used from LINZ networks and the public internet
    - [ ] Availability: System available 24 hours a day and 7 days a week, this does not include
          maintenance windows < 4 hours and does not include operational support
    - [ ] Recoverability: RPO of fully imported datasets < 4 hours, RTO of a single 3 TB dataset <
          12 hours

**Comment by billgeo** [comment]
Tested this and
