### ISSUE TITLE
Publish STAC Catalog

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#1709]
### User Story

So that I can crawl, browse and search the Geostore metadata using existing tools such as [STAC Browser](https://github.com/radiantearth/stac-browser), as an external developer or analyst, I want the geostore STAC metadata freely and openly published as a catalog on the public internet.

#### Acceptance Criteria

-  [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]

#### Additional context

LINZ has invested alot in the STAC standard and also has an interest in supporting and building the standard for LINZ and for New Zealand inc. So one of the drivers for this is to support and develop the standard and associated tools for the greater community.

LINZ and our partners adn customers also need to find our data, and some datasets like Historic Imagery are quite difficult to search and find at the moment. So this is the other main driver for this story.

Currently the metadata files are stored alongside the asset files so we will want to consider how we might provide the metadata openly and not share the assets (there are additional considerations to sharing the assets, such as controlling egress costs). Although initially the Historic Imagery data can probably be also made public, so a very simple solution for the next 6-12 months could be to make the whole bucket public and http.

There are two main types of STAC catalog, static linked json files and dynamic APIs. Blog post [here](https://medium.com/radiant-earth-insights/static-spatiotemporal-asset-catalogs-in-depth-710530934a84) about the implications of static vs dynamic, and here's some [overview comparison](https://stacspec.org/en/about/stac-spec/). Also some stac best practice guidelines [here](https://github.com/radiantearth/stac-spec/blob/master/best-practices.md), including a section on requestor pays. 

See also, [STAC-spec API](https://github.com/radiantearth/stac-api-spec)  and [list of tools](https://stacindex.org/ecosystem?category=API) that build dynamic STAC APIs.

And [here for a list of existing catalogs](https://stacindex.org/catalogs) (can be filtered by static or dynamic catalogs).

#### Tasks

-  [ ] ...
-  [ ] ...

#### Definition of Ready

-  [ ] This story is **ready** to work on
   -  [ ] Independent (story is independent of all other tasks)
   -  [ ] Negotiable (team can decide how to design and implement)
   -  [ ] Valuable (from a user perspective)
   -  [ ] Estimate value applied (agreed by team)
   -  [ ] Small (so as to fit within an iteration)
   -  [ ] Testable (in principle, even if there isn't a test for it yet)
   -  [ ] Environments are ready to meet definition of done
   -  [ ] Resources required to implement will be ready
   -  [ ] Everyone understands and agrees with the tasks to complete the story
   -  [ ] Release value (e.g. Iteration 3) applied
   -  [ ] Sprint value (e.g. Aug 1 - Aug 15) applied

#### Definition of Done

-  [ ] This story is **done**:
   -  [ ] Acceptance criteria completed
   -  [ ] Automated tests are passing
   -  [ ] Code is peer reviewed and pushed to master
   -  [ ] Deployed successfully to test environment
   -  [ ] Checked against
          [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
   -  [ ] Relevant new tasks are added to backlog and communicated to the team
   -  [ ] Important decisions recorded in the issue ticket
   -  [ ] Readme/Changelog/Diagrams are updated
   -  [ ] Product Owner has approved acceptance criteria as complete
   -  [ ] Meets non-functional requirements:
      -  [ ] Scalability (data): Can scale to 300TB of data and 100,000,000 files and ability to
             increase 10% every year
      -  [ ] Scability (users): Can scale to 100 concurrent users
      -  [ ] Cost: Data can be stored at < 0.5 NZD per GB per year
      -  [ ] Performance: A large dataset (500 GB and 50,000 files - e.g. Akl aerial imagery) can be
             validated, imported and stored within 24 hours
      -  [ ] Accessibility: Can be used from LINZ networks and the public internet
      -  [ ] Availability: System available 24 hours a day and 7 days a week, this does not include
             maintenance windows < 4 hours and does not include operational support
      -  [ ] Recoverability: RPO of fully imported datasets < 4 hours, RTO of a single 3 TB dataset
             < 12 hours

**Comment by billgeo** [comment]
This has been replaced by other stories. Closing,
