### ISSUE TITLE
Rename dataset with a hash in s3 prefix

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#1794]
This dataset has a hash in the s3 prefix of the dataset title, should be renamed to remove the hash from the prefix.

e.g. `s3://linz-geostore/historical-aerial-imagery-survey-2548-01G6M7TZM7376J714Q1Y3TQ9FV/` should be renamed`s3://linz-geostore/historical-aerial-imagery-survey-2548/`

## Tasks

- [x] Re-import `s3://linz-geostore/historical-aerial-imagery-survey-2548-01G6M7TZM7376J714Q1Y3TQ9FV/` into the same dataset:

   ```
   $ geostore version create --dataset-id=01G6M7TZM7376J714Q1Y3TQ9FV --metadata-url=s3://linz-geostore/historical-aerial-imagery-survey-2548-01G6M7TZM7376J714Q1Y3TQ9FV/collection.json --s3-role-arn=arn:aws:iam::715898075157:role/s3-users
   2022-07-01T11-24-34-140Z_CV8D3JDRYW1JXB71	arn:aws:states:ap-southeast-2:715898075157:execution:processingproddatasetversioncreation41FE9F76-0Y29aYCpqBN5:2022-07-01T11-24-34-140Z_CV8D3JDRYW1JXB71
   ```
- [x] `aws s3 cp s3://linz-geostore/catalog.json .`
- [x] Modify path to dataset in local `catalog.json`
- [x] `aws s3 cp catalog.json s3://linz-geostore/catalog.json`
- [x] Delete S3 files: `aws s3 rm --recursive s3://linz-geostore/historical-aerial-imagery-survey-2548-01G6M7TZM7376J714Q1Y3TQ9FV/`
- [x] Ask Gokul to delete the delete markers returned by `aws s3api list-object-versions --bucket=linz-geostore --prefix=historical-aerial-imagery-survey-2548-01G6M7TZM7376J714Q1Y3TQ9FV/ | jq .DeleteMarkers`
- [x] ~~Document or automate the process for future reference.~~ We won't need to do this anymore, because the ULID suffix is no longer added to dataset prefixes.

**Comment by billgeo** [comment]
Looks good. ALthough I was thinking we should document this for any time we need to rename a dataset which I think will likely happen again. But let's leave it for then. This is a good record of what you did anyway.

```bash
[nix-shell:~/dev/geostore]$ geostore dataset list | grep 2548
historical-aerial-imagery-survey-2548
```

![image.png](https://images.zenhubusercontent.com/5ab31db94b5806bc2bcbe143/80436c60-1858-446a-9825-ee74ce5f6a6b)

**Comment by gokskrish** [comment]
Delete Markers are removed

**Comment by billgeo** [comment]
Need to do this to delete the old versions of the old prefix.

1. Get the versions to delete
    `aws s3api list-object-versions --bucket=linz-geostore --prefix=historical-aerial-imagery-survey-2548-01G6M7TZM7376J714Q1Y3TQ9FV | jq -c '.Versions [] | {Key,VersionId}' > versions_to_delete.json`
1. Read through them and double check they are the right prefix / keys
    `vim versions_to_delete.json`
1. Delete the versions
    `for i in $(cat versions_to_delete.json); do key=$(jq -r '.Key' <<< $i); version=$(jq -r '.VersionId' <<< $i); aws s3api delete-object --bucket linz-geostore --key $key --version-id $version --profile li-geostore-prod; done`

**Comment by billgeo** [comment]
Done. 

`Bills-MacBook-Pro:dev bill$ aws s3api list-object-versions --bucket=linz-geostore --prefix=historical-aerial-imagery-survey-2548-01G6M7TZM7376J714Q1Y3TQ9FV --profile li-geostore-prod`
[nothing returned]

**Comment by billgeo** [comment]
@l0b0 can you please review what I did here and close if everything is fine?

**Comment by l0b0** [comment]
LGTM.
