### ISSUE TITLE
Move OIDC provider to separate repo

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#1832]
### Enabler

So that we can easily deploy OIDC providers and share this logic with other projects, we want to move [the OIDC provider branch](https://github.com/linz/geostore/tree/feat/oidc-provider) to [another repo](https://github.com/linz/oidc-provider).

#### Acceptance Criteria

-  [ ] Separate repo with code & documentation to deploy an OIDC provider for an arbitrary AWS account and GitHub repos

#### Tasks

- [ ] Linting & formatting like in the Geostore
- [ ] ~~CI pipeline to run the above~~
- [ ] Thorough documentation for running the deployment manually (but see below)

#### Optional/non-tasks

- [ ] CI pipeline to deploy the OIDC provider. This would be handy to have a record of our deployments, but it would have to be parameterised and we'd need to make sure AWS credentials are not shown in any logs, despite being fed manually to each run.
