### ISSUE TITLE
Use lock file for Pip installs

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#1991]
### Enabler

So that the Geostore uses specific and up-to-date versions of Poetry (to easily resolve any version-specific problems), we want to use a lock file and configure Dependabot to update it.

#### Acceptance Criteria

-  [ ] All instances of `pip install` use a `requirements.txt` file *with hashes*
-  [ ] The `requirements.txt` file(s) are configured in Dependabot

#### Tasks

-  [ ] Create `requirements.txt` with Pip and Poetry, perhaps using `pip-compile` like [this example](https://github.com/dependabot/dependabot-core/commit/15c08c7f4c2b3dc7a32ed54bbf57a7edfac993ec#diff-7aaed1e0a9ca67e71040a358f5ef91258093f6e898e2a3eb887e6a84b2b45f86) to add the hashes, referencing the existing `pip==21.3.1` and `poetry==1.1.11` in `geostore/Dockerfile`.
-  [ ] Change all instances of `pip install` to reference the file above
- [ ] Configure Dependabot to update this file

Post-merge tasks:

- [ ] Run Dependabot and verify that it updates the versions
