### ISSUE TITLE
Monitor SQS Queue: Why did it break? How can we prevent this in the future?

### ISSUE THREAD

**Issue by mfwightman** [linz/geostore#2106]
## Problem
The SQS Queue broke, we have spent some time getting it going again.
Now we need to reflect and work out why it went wrong.

## Tasks
- [ ] Investigation into why something went wrong with the SQS Queue.
- [ ] Look at what we can do to put systems in place to prevent this in the future.
- [ ] Share results in some way with team.
