### ISSUE TITLE
Upgrade to Python 3.10

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#2127]
### Enabler

So that we can use the most recent language features, we want to upgrade Python from 3.9 to 3.10.

So that [some reason], we want to [do something]

#### Acceptance Criteria

- [ ] CDK Lambda functions use the Python 3.10 Docker image
- [ ] .python-version has version 3.10.0 or later
- [ ] pyproject.toml limits Python version to between 3.10 and 3.11 (exclusive)
- [ ] CI workflows use Python 3.10

#### Tasks

-  [ ] ...
-  [ ] ...

**Comment by Jimlinz** [comment]
Unfortunately support for the [latest lambda Python version](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) is still 3.9

Python 3.11 is already out so it is a bit disappointing that AWS is slow to upgrade
