### ISSUE TITLE
Spike: deploy and test stac-fastapi

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#2228]
So that we can confidently productionise a STAC API and indexing tool we want to install and import LINZ data to the stac-fastapi.

### Tasks

- [x] Deploy and configure the tool in a LINZ AWS account (developers geostore-nonprod[1/2/3] account)
- [x] Import LINZ's current production metadata (excepting the root catalog) in the Geostore production bucket.
- [x] Brief results against the assessment criteria below should be captured in confluence. 

See [confluence page for research done so far.](https://toitutewhenua.atlassian.net/wiki/spaces/LGDL/pages/127796416/STAC+API+Options)

Assessment criteria:

- cost is acceptable (storage, compute, requests)
- can ingest our data automatically from an S3 bucket with acceptable operational or development overhead
- the API functionality works well and does what we expect
- can index LINZ STAC metadata extensions and make available for search
- easily deployed, maintained and configured
- performs well with LINZ's full dataset (search speed etc)
- list any missing functionality or components

**Comment by billgeo** [comment]
Closing this as done. Thanks @AmrouEmad
