### ISSUE TITLE
Spike: deploy and test Franklin

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#2229]
So that we can confidently productionise a STAC API and indexing tool we want to install and import LINZ data to [Franklin](https://toitutewhenua.atlassian.net/wiki/spaces/LGDL/pages/131532266/Franklin).

### Tasks

- [ ] Deploy and configure the tool in a LINZ AWS account (devs nonprod Geostore account (1,2 or 3))
- [ ] Import LINZ's current production metadata (excepting the root catalog) in the Geostore production bucket.
- [ ] Brief results against the assesment criteria below should be captured in confluence. 

See [confluence page for research done so far.](https://toitutewhenua.atlassian.net/wiki/spaces/LGDL/pages/127796416/STAC+API+Options)

Assessment criteria:

- cost is acceptable (storage, compute, requests)
- can ingest our data automatically from an S3 bucket with accptable operational or development overhead
- the API functionality works well and does what we expect
- can index LINZ STAC metadata extensions and make available for search
- easily deployed, maintained and configured
- performs well with LINZ's full dataset (search speed etc)
- list any missing functionality or components

**Comment by Jimlinz** [comment]
Franklin isn't a good fit for Geostore. The documentation is very light (almost non-existence). The instructions are outdated (they don't work). It also looks like the project has been abandoned??? Last human commit was a while back...

**Comment by billgeo** [comment]
Closing this as done. Thanks @Jimlinz
