### ISSUE TITLE
Replace Pip, Poetry and NPM with Nix?

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#2423]
### Enabler

So that we have to deal with only a single packaging system, we want to use only Nix.

Pros:

- We'd only ever need to update [a single file (`nixpkgs.json`)](https://github.com/linz/geostore/blob/5c1b2aed5cc2a958340352da5a36b08364d658ae/nixpkgs.json) to bump all the packages we use. If for any reason we need to use different packages in some part of the system that would be as simple as modifying and referencing a copy of `nixpkgs.json`, which could then trivially be merged back into the original `nixpkgs.json` when the packages end up being in sync again.
- We wouldn't need to use [poetry2nix](https://github.com/nix-community/poetry2nix/), which, while excellent, is always playing catch-up with changing Python packages.
- Faster builds, since we'd be using the official Nix cache for probably every package except linz-logger.
- Reproducible builds, including Docker images.
- `./reset-dev-env.bash` would be replaced with `nix-shell` or `direnv allow`.

Cons:

- Nix has a famously steep learning curve, but [they are working on it](https://discourse.nixos.org/t/documentation-team-flattening-the-learning-curve/20003).
- We would not be able to support non-POSIX platforms like Windows. Nix only supports POSIX platforms (Linux, BSD, Mac OS, etc.).
- Anyone who has set up their environment to work with [Ubuntu](https://github.com/linz/geostore/blob/8e36b0a0e7d59ba3161cd567ceff7b43731a9100/README.md?plain=1#L66-L143) would have to install and [use Nix](https://github.com/linz/geostore/blob/8e36b0a0e7d59ba3161cd567ceff7b43731a9100/README.md?plain=1#L145-L154) instead. This is *much* simpler than the Ubuntu setup, but it *is* an extra step.
- We might want to package some things which are not yet in nixpkgs. For example, it looks like [boto3-stubs is not yet in nixpkgs](https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=boto3-stubs). [I've already released some packages on nixpkgs](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aclosed+author%3Al0b0), and it's not particularly difficult.

#### Acceptance Criteria

-  [ ] No mentions of Poetry in the repo.
-  [ ] No more `npm` commands in the repo.
- [ ] No more `pip` commands in the repo.

#### Additional context

This would require developers to use Nix for development, rather than continuing to support a non-Nix workflow.

#### Tasks

- [ ] Move the packages mentioned in the `tool.poetry` sections from `pyproject.toml` to a Nix file
- [ ] Remove `poetry.*`
- [ ] Remove `geostore/*.txt`
- [ ] Change `bundle.bash` to build using Nix. This could possibly involve [creating Docker containers using Nix](https://nix.dev/tutorials/building-and-running-docker-images).
- [ ] Replace Dependabot with a tool which supports Nix (Renovate?)
- [ ] Remove `generate-requirements-files.bash`
- [ ] Remove `pip`, `pip-tools`, `poetry`, and `poetry2nix` from Nix shell definition
- [ ] Remove `package*.json`
- [ ] Remove Nix shell `shellHook`, since it would no longer be necessary
- [ ] Remove `reset-dev-env.bash`
- [ ] Convert `infrastructure/constructs/lambda_layers/botocore` to use Nix, if possible
- [ ] Update relevant documentation
- [ ] Ensure local development works easily. This should be as simple as copying the commands from the GitHub Actions.
