### ISSUE TITLE
Spike: How to implement LINZ Centralized Logging

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#247]
### Enabler

So that we know the work involved in incorporating Kibana, Elasticsearch and LINZ centralised logging, we want investigate how to use Kibana, Elasticsearch and LINZ centralised logging.

#### Acceptance Criteria

- [ ] We know how to aggregate or send logs from the entire application into Elasticsearch(?)
- [ ] We know how we will access logs, filters, reports  etc with with frontend like Kibana
- [ ] We know how we can can setup up alerts of filtered log messages. e.g. Slack channels (e.g. import has finished, import has failed for reason xx)

#### Additional context

For ideas and common LINZ patterns:

- See Basemaps squad/repo
- See STEP Enablement squad/repo
- LINZ centralized logging docs: https://confluence.linz.govt.nz/display/PuC/Centralized+logging+for+AWS+landing+zone

#### Tasks

- [x] Talk to Basemaps and or enablement squad about how to use it
- [x] Read any documentation
- [ ] Update the user stories with detail about how we will implement it

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Hi @l0b0, you put a question mark at the end of the title. Does this need to be a spike for us to choose the best method?

**Comment by l0b0** [comment]
It was a quick suggestion/question based on a chat with @blacha. It probably needs to be a spike to establish what the current Elasticsearch solution looks like, how hard it would be to integrate with it, and whether it does what we want.

**Comment by billgeo** [comment]
Sounds good to me. Will add the spike label.

**Comment by billgeo** [comment]
Apparently there are some changes happening to the LINZ logging system which may make it easier for us to use?

**Comment by imincik** [comment]
LINZ Central logging is in undergoing upgrade which will result in logging process and setup simplification. In [Logging documentation](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=83649508), top diagram is showing new state and lower one the old one.

* [aws-log-config](https://github.com/linz/aws-log-config) will be used to configure log shipping. 
* aws-log-config depends on [linzjs/cdk-elastic-shipper](https://github.com/linz/elasticsearch-shipper)
* [ept-central-applogs](https://github.com/linz/ept-central-applogs) is used for deployment of whole LINZ Central Logging solution

In new version of LINZ Centralized Logging all logs from product AWS account should be automatically imported to LINZ Centralized Logging system based on aws-log-config configuration.

**Comment by billgeo** [comment]
Thanks @imincik . So do we all the info we can get? Can we update the tasks in #712 ?
If so, please update it and I think we close this as done.

**Comment by billgeo** [comment]
Also, do you understand how we will set up Kibana and Slack notifications?

**Comment by imincik** [comment]
I would expect Kibana interface to be created automatically for each product, but I'll check that. According logging design diagram, Slack messages are sent from Kibana if errors happen, but I don't know where you configure channel names.

I'll check those details in #cop-logging.

**Comment by billgeo** [comment]
Thanks @imincik. When you have all the info we need. Can you please update #712 and move this to PO review.

**Comment by imincik** [comment]
> Also, do you understand how we will set up Kibana and Slack notifications?

1. Kibana needs space created, it is not automatic
2. Slack messages are configured by ElasticSearch configuration (see: https://github.com/linz/basemaps-team/blob/master/config/elasticsearch/watch.aws.AssumeRoleWithSAML.json)

**Comment by imincik** [comment]
> Thanks @imincik. When you have all the info we need. Can you please update #712 and move this to PO review.

This is already done now.
