### ISSUE TITLE
Lock down dependency versions in pyproject.toml?

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#2503]
### Enabler

So that Poetry doesn't constantly [update irrelevant packages when changing the lock file](https://github.com/python-poetry/poetry/issues/4288), we want to set specific dependency versions in `pyproject.toml`.

#### Acceptance Criteria

-  [ ] Each dependency in `pyproject.toml` is set to its current version.

#### Additional context

Pros:

- No irrelevant package updates when doing lock file changes
- `pyproject.toml` is explicit about which versions we've actually tested on

Cons:

- Bigger Dependabot commits

#### Tasks

-  [ ] Set package versions in `pyproject.toml` to the ones currently in `poetry.lock`

#### Definition of Ready

-  [ ] This story is **ready** to work on
   -  [ ] Negotiable (team can decide how to design and implement)
   -  [ ] Valuable (from a user perspective)
   -  [ ] Estimate value applied (agreed by team)
   -  [ ] Small (so as to fit within an iteration)
   -  [ ] Testable (in principle, even if there isn't a test for it yet)
   -  [ ] Environments are ready to meet definition of done
   -  [ ] Resources required to implement will be ready
   -  [ ] Everyone understands and agrees with the tasks to complete the story
   -  [ ] Release value (e.g. Iteration 3) applied
   -  [ ] Sprint value (e.g. Aug 1 - Aug 15) applied

#### Definition of Done

-  [ ] This story is **done**:
   -  [ ] Acceptance criteria completed
   -  [ ] Automated tests are passing
   -  [ ] Code is peer reviewed and pushed to master
   -  [ ] Deployed successfully to test environment
   -  [ ] Checked against
          [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
   -  [ ] Relevant new tasks are added to backlog and communicated to the team
   -  [ ] Important decisions recorded in the issue ticket
   -  [ ] Readme/Changelog/Diagrams are updated
   -  [ ] Product Owner has approved acceptance criteria as complete
   -  [ ] Meets non-functional requirements:
      -  [ ] Scalability (data): Can scale to 300TB of data and 100,000,000 files and ability to
             increase 10% every year
      -  [ ] Scability (users): Can scale to 100 concurrent users
      -  [ ] Cost: Data can be stored at < 0.5 NZD per GB per year
      -  [ ] Performance: A large dataset (500 GB and 50,000 files - e.g. Akl aerial imagery) can be
             validated, imported and stored within 24 hours
      -  [ ] Accessibility: Can be used from LINZ networks and the public internet
      -  [ ] Availability: System available 24 hours a day and 7 days a week, this does not include
             maintenance windows < 4 hours and does not include operational support
      -  [ ] Recoverability: RPO of fully imported datasets < 4 hours, RTO of a single 3 TB dataset
             < 12 hours

**Comment by Jimlinz** [comment]
If package `X` depends on `Y version 1.1`, we should definitely pin it. 
The only downside I can see is if `Y` sends out a security patch, we might be unaware until package `x` updates its dependencies?

**Comment by l0b0** [comment]
> If package `X` depends on `Y version 1.1`, we should definitely pin it.

We're already pinning everything in poetry.lock, this is more about working around how Poetry aggressively tries to update packages when basically doing anything with the lock file.

> The only downside I can see is if `Y` sends out a security patch, we might be unaware until package `x` updates its dependencies?

This is taken care of by Dependabot and the [alerts we've enabled](https://github.com/linz/geostore/security).
