### ISSUE TITLE
Avoid copying entire repository into CDK asset

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#253]
### Enabler

So that deployments can take a reasonable amount of time, we want to avoid copying the entire repository into `cdk.out/asset.[hash]` on every deployment.

#### Acceptance Criteria

- [x] Avoid copying unnecessary files into *any* of the CDK assets. The .git directory and cdk.out itself are especially important.

#### Additional context

Will need some investigation to figure out which assets end up copying the entire repository and why. The fix might be specific to those assets.

Workaround: `rm -rf cdk.out` before every CDK command.

#### Tasks
- [x] Work out which assets include the whole repository
- [x] Work out which exclusion methods are appropriate for each of those assets
- [x] Implement the actual exclusion
- [x] Verify

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [x] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Not really sure how to prioritise this one. We might have to discuss the pros and cons at Backlog refinement.
