### ISSUE TITLE
chore: Upgrade to Python 3.9

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#295]
### Enabler

So that we can use the most recent language features, we want to upgrade Python from 3.8 to 3.9.

#### Acceptance Criteria

- [x] CDK Lambda functions use the Python 3.9 Docker image
- [x] .python-version has version 3.9.0 or later
- [x] pyproject.toml limits Python version to between 3.9 and 3.10 (exclusive)
- [x] CI workflows use Python 3.9

#### Additional context

We need to wait for AWS to [support](https://docs.aws.amazon.com/lambda/latest/dg/python-image.html) [Python 3.9](https://github.com/aws/aws-lambda-base-images/issues/11) Lambda functions.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Hey @l0b0 did you do any work on this this sprint. Or did you close if for another reason?

**Comment by l0b0** [comment]
I finished this, but forgot to link the [PR](https://github.com/linz/geostore/pull/2055).

**Comment by billgeo** [comment]
Cool. Thanks. Just retrospectively adding an estimate to make the sprint reporting work. 😄
