### ISSUE TITLE
Make sure the dataset contains at least one asset file

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#329]
### User Story

So that I'm sure the dataset is valid, as a dataset maintainer, I want to be notified if the dataset has no assets.

#### Acceptance Criteria

- [ ] Given a dataset with no assets, when I try and import to a new version, then the new version isn't created and a useful message returned to me

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Hey @l0b0 .

Not sure if I doing this completely right, but when I tried this on nonprod AWS account I get this output. Would have expected some useful error output?

```
{
  "status_code": 200,
  "body": {
    "step_function": {
      "status": "Failed"
    },
    "validation": {
      "status": "Skipped",
      "errors": []
    },
    "metadata_upload": {
      "status": "Skipped",
      "errors": []
    },
    "asset_upload": {
      "status": "Skipped",
      "errors": []
    }
  }
}
```

Using attached collection.json

**Comment by billgeo** [comment]
```
{
    "id": "tasman_rural_2003_1m_RGB",
    "stac_version": "1.0.0",
    "type": "Collection",
    "description": "Orthophotography for the Tasman region taken in 2003.**\n\nImagery was captured for the \u2018Tasman District Council\u2019 by NZ Aerial Mapping Ltd, 208 Warren Street, PO Box 6, Hastings 4156, New Zealand\n\nData has subsequently been provided to LINZ and this comprises:\n- 11 x ortho-rectified RGB GeoTIFF images in NZTM projection, tiled into the LINZ Standard 1:10,000 tile layout\n- Tile layout in NZTM projection containing relevant information.\n\nThe supplied imagery is in terms of New Zealand Transverse Mercator (NZTM) map projection. The products are tiled into NZTopo50 1:10,000 tiles. Please refer to the supplied tile layout shape file for specific details, naming conventions, etc. \n\nImagery supplied as 100cm pixel resolution (1m GSD), 3-band (RGB) uncompressed GeoTIFF. The final spatial accuracy is +/-15m (@ 90% confidence).\n\nIndex tiles for this dataset are available as layer [Tasman 1m Rural Aerial Photos Index Tiles (2003)](http://data.linz.govt.nz/layer/1891)\n",
    "links": [
        {
            "rel": "self",
            "href": "collection.json",
            "type": "application/json"
        }
    ],
    "title": "Tasman 1m Rural Aerial Photos (2003)",
    "linz:security_classification": "Unclassified",
    "linz:created": "2003-01-01T00:00:00.000Z",
    "linz:updated": "2003-01-01T00:00:00.000Z",
    "license": "CC-BY-4.0",
    "extent": {
        "spatial": {
            "bbox": [
                [
                    172.05956425817075,
                    -40.91288934049462,
                    172.51785842526388,
                    -40.58580513954452
                ]
            ]
        },
        "temporal": {
            "interval": [
                [
                    "2003-01-01T00:00:00Z",
                    "2003-12-31T00:00:00Z"
                ]
            ]
        }
    },
    "stac_extensions": [
        "https://linz.github.io/stac/v0.0.4/linz/schema.json"
    ],
    "keywords": [
        "Imagery",
        "New Zealand",
        "Aerial",
        "Rural"
    ],
    "providers": [
        {
            "name": "Tasman District Council",
            "roles": [
                "licensor"
            ],
            "url": "https://www.tdc.govt.nz"
        },
        {
            "name": "NZ Aerial Mapping Ltd",
            "roles": [
                "producer"
            ],
            "url": "https://data.linz.govt.nz"
        },
        {
            "name": "LINZ",
            "roles": [
                "host"
            ],
            "url": "https://data.linz.govt.nz"
        }
    ],
    "properties": {
        "created": "2020-07-16T04:29:46.349530Z",
        "proj:epsg": 2193,
        "eo:gsd": 1.0,
        "eo:bands": [
            {
                "name": "Red",
                "common_name": "red",
                "description": "Band 0 Block=128x128 Type=Byte"
            },
            {
                "name": "Green",
                "common_name": "green",
                "description": "Band 1 Block=128x128 Type=Byte"
            },
            {
                "name": "Blue",
                "common_name": "blue",
                "description": "Band 2 Block=128x128 Type=Byte"
            }
        ],
        "start_datetime": "2003-01-01T00:00:00.000Z",
        "end_datetime": "2003-12-31T00:00:00.000Z",
        "datetime": "2003-01-01T00:00:00.000Z",
        "eo:platform": "UNSPECIFIED",
        "eo:instrument": "Unknown",
        "linz:accuracy": 0.15,
	"other:test_attribute": "some test value"
    },
    "assets": {
    }
}

```

**Comment by l0b0** [comment]
The last entry in the step function log I have is Sep 23, 2021 08:56:31.826 PM; is that the run you did? The log entry says

```
{
  "errorMessage": "",
  "errorType": "NoAssetsInDatasetError",
  "stackTrace": [
    "  File \"/var/task/backend/check_stac_metadata/task.py\", line 63, in lambda_handler\n    validator.run(event[METADATA_URL_KEY])\n",
    "  File \"/var/task/backend/check_stac_metadata/utils.py\", line 103, in run\n    raise NoAssetsInDatasetError\n"
  ]
}
```

which fits with your collection.json, but I'd have to look into why the exception isn't propagated to the end user.

**Comment by billgeo** [comment]
Looks good. Thanks @l0b0
