### ISSUE TITLE
Provide readonly access to the S3 bucket for all of LINZ

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#345]
### User Story

So that I can browse and extract data with the S3 API, as a LINZ Data Analyst or Developer, I want authorization to list, browse, and extract (readonly role) data from the Data Lake S3 bucket.

#### Acceptance Criteria

- [ ] Given I have a LINZ AD account (part of the 'All-LINZ-Staff' AD group), when  I open myapplications.microsoft.com, then I can assume the role that allows me to read S3 bucket data from the data lake 
- [ ] ~~Given I have a LINZ AWS account (member of LINZ Org), when I attempt to assume the role from my LINZ AWS account, then I can assume the role that allows me to read S3 bucket data from the data lake~~ 
- [ ] Given I have no valid LINZ AD account or a LINZ AWS account, when I open myapplications.microsoft.com, then I can not assume the role that allows me to read S3 bucket data from the data lake 

#### Tasks

- [ ] Give access to all LINZ users, use existing 'all of LINZ' AD group - 2
- [ ] Test manually

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
All the AD roles appear to be broken on nonprod. Could you get this fixed @MitchellPaff ?

**Comment by billgeo** [comment]
Tested and working just fine. Thanks @MitchellPaff
