### ISSUE TITLE
Support importing from other versions of STAC metadata

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#346]
### User Story

So that I can easily import my existing datasets in the Data Lake 2, as a Aerial Imagery Maintainer, I want to import my data and metadata from STAC 0.8.1 format (and converting to current DL version?)

#### Acceptance Criteria

- [ ] Given STAC metadata 0.8.1 or later, when I start an import, then metadata is validated (or converted?) to current DL STAC profile version
- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]

#### Additional context

This? https://www.skypack.dev/view/@radiantearth/stac-migrate

Steps to manually update Aerial Imagery metadata (v0.8.1) to 1.0.0-rc.1:
1. Add "type": "Collection",
2. Change "stac_version": "0.8.1", to "stac_version": "1.0.0-rc.1",
3. Change NZ Aerial Mapping url from "url": "unknown" to "url: "https://www.linkedin.com/company/nz-aerial-mapping-limited-sa/"
4. Change datetime format from '2003-01-01 00:00:00.000Z' to '2003-01-01T00:00:00.000Z'

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
This will likely be done outside the geostore product. Closing.
