### ISSUE TITLE
Mitigation of accidental or malicious data deletion or modification in production environment

### ISSUE THREAD

**Issue by imincik** [linz/geostore#375]
### User Story

So that production deployment of Data Lake system and it's content is protected against accidental or malicious deletion or modification, as a Data Lake Maintainer, I want to ensure content is unlikely to be lost or corrupted by implementing suitable system and data safety configuration.

Note: we can rely on extremely high availability and reliability of AWS S3 service for this and only need to mitigate accidental or malicious actions by LINZ data maintainers or admins, by using finegrained access controls of AWS services.

https://confluence.linz.govt.nz/pages/viewpage.action?spaceKey=LGDL&title=Data+Lake+S3+Storage+Bucket+Access+Controls

#### Acceptance Criteria

- [ ] Given Data Lake is deployed to production, when attempting to delete production Data Lake AWS Stack (by mistake), then then it is explicitly denied
- [ ] Given Data Lake is deployed to production, when attempting to delete production Data Lake Storage Bucket (by mistake), then it is explicitly denied
- [ ] Given Data Lake is deployed to production, when attempting to disable production Data Lake Storage Bucket versioning (by mistake), then it is explicitly denied
- [ ] Given Data Lake is deployed to production, when attempting to delete production Data Lake Datasets any database tables (by mistake), then it is explicitly denied
- [ ] Given Data Lake is deployed to production, when attempting to permanently delete any files from production Data Lake Storage Bucket (by mistake or for any purpose), then it is explicitly denied

#### Tasks

- [x] Document list of things we shouldn't be able to delete for Terence to create IAM rules
- [x] Terence edits roles and provide all steps/information to Prod Team to make it repeatable/documented
- [ ] Test production restrictions

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Thanks @imincik. This will be good to do. I don't see this as a prerequisite for the first release though. So I'm tempted to put this in release 2 or 3. Feel free to convince me otherwise though.

**Comment by billgeo** [comment]
After discussion with @terencewhitenz last week have decided to do this instead of traditional Backup and Restore.
@imincik can you please update this with acceptance criteria and tasks based on discussion with Terence last week?

**Comment by billgeo** [comment]
I've edited the user story slightly, please review.

**Comment by imincik** [comment]
Acceptance Criteria updated

**Comment by billgeo** [comment]
Sounds like we have what we need here. It's been tested by @MitchellPaff . Closing...
