### ISSUE TITLE
Auto-populate 'user' and 'owning group' information when creating a dataset

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#515]
### User Story

So that my username and data maintenance group is stored reliably, as a Data Maintainer, I **don't** want to specify a user and 'owning group' for a dataset manually (free text), ideally this would be populated automatically from my LINZ credentials.

Note: what will happen with an automated pipeline? Who is the 'user' for this?

#### Acceptance Criteria

- [ ] Given I am a valid authorized user, when I create a dataset, then 'user' and 'data maintenance group' is auto-populated from my AWS username and role
- [ ] Given I am a valid automated pipeline user, when I create a dataset, then 'user' and 'data maintenance group' is auto-populated from my AWS username and role
- [ ] Given I am a valid authorized user, when I create a dataset, then only need to provide the 'title' of the dataset.

#### Additional context

Might need API Gateway to be able to retrieve this information.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
@imincik could you please refine this story? Add tasks, acceptance criteria and estimates?
Let me know if you want to discuss.

**Comment by billgeo** [comment]
Group and maintainer is now stored in the metadata and is no longer submitted to the geostore as parameters
