### ISSUE TITLE
Validate imports against the LINZ STAC extension

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#517]
### User Story

So that I can ensure my metadata has all the LINZ required metadata elements, as Data Maintainer, I want my metadata validated against all mandatoryelements of the LINZ metadata extension

#### Acceptance Criteria

- [ ] Given any LINZ metadata element is missing, when I try to import my data, then a metadata validation error is returned
- [ ] Given any LINZ metadata element is incorrect (what can we check here? data types?), when I try to import my data, then a metadata validation error is returned

#### Tasks

- [ ] Validate against the LINZ metadata profile

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by dwsilk** [comment]
I made a start by writing up some README's for generic LINZ metadata [here](https://github.com/linz/STAC/blob/docs/linz_dataset_extension/extensions/linz_dataset/README.md) and [here](https://github.com/linz/STAC/blob/docs/linz_metadata_extension/extensions/linz_metadata/README.md) but that's just two very basic groupings, there probably need to be more.

We're also wondering whether to create some [pydantic](https://pydantic-docs.helpmanual.io/usage/schema/) models and generate the JSON Schema for the extensions from those? A consistent approach would be good. [stac-pydantic](https://github.com/stac-utils/stac-pydantic) may be helpful here too.

**Comment by billgeo** [comment]
Thanks @dwsilk

**Comment by billgeo** [comment]
Q's for refinement meeting

Is this a duplicate of #78? 
If so, why the difference in estimate? 
Was that because we were thinking we'd create all the json-schemas in this story?
