### ISSUE TITLE
Support data extract by OpenTopography

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#528]
### User Story

So that I can publish my point cloud elevation data to my users, as a Data Maintainer (Elevation), I want my data publishing channel, OpenTopo, to extract all the data they need from the Geostore into [OpenTopography](https://portal.opentopography.org) (3rd party service).

See https://portal.opentopography.org

Note: current process is to provide data to Open Topography via FTP server, but they can copy data to their AWS account in the US.

#### Acceptance Criteria

- [ ] Given a LiDAR dataset is ready for publishing, when I notify (email?) OpenTopography, then they are able to extract the data they need
- [ ] ~~Given a non LiDAR dataset and a LiDAR dataset, when I notify OpenTopography, then the non-LiDAR dataset is unable to be extracted (Could do this one later?) ~~

#### Tasks

- [x] Add some (test?) LiDAR data
- [x] Set up role for Opentopo to assume
- [x] Test role access with Opentopo dev (Matt Beckley)
- [x] Confirm data copied successfully
- [ ] Confirm egress fees are as expected

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by imincik** [comment]
I created test environment of our new Geostore system and uploaded test file called "test.zero".

Steps to test access:

* Assume opentopography-s3-access-read-test role (this will give you temporary credentials which you are going to need in next step)

```
$ aws sts assume-role --role-arn "arn:aws:iam::099672678701:role/opentopography-s3-access-read-test" --role-session-name test --external-id opentopography-bahX0
```

* Using credentials from previous step, download "test.zero" file
```
$ AWS_ACCESS_KEY_ID=<AWS_ACCESS_KEY_ID> AWS_SECRET_ACCESS_KEY=<AWS_SECRET_ACCESS_KEY> AWS_SESSION_TOKEN="<AWS_SESSION_TOKEN>" aws s3 cp s3://test-linz-geostore/test.zero /tmp/
```

**Comment by imincik** [comment]
Matt Beckley confirmed that he was successfully able to download test file using `opentopography-s3-access-read-test` role.
