### ISSUE TITLE
Cost effective way to update a dataset

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#559]
### User Story

So that I can update the data or metadata easily and frequently, as a Data Maintainer, I want to submit only the data/metadata that I want to change.

#### Acceptance Criteria

- [ ] Given a dataset that already has data, when I request an update with a file to add to the dataset, then that file is added to the existing dataset
- [ ] Given a dataset that already has data, when I request an update with a file to be removed, then that file is removed (archived? hidden?) from the dataset
- [ ] Given a dataset that already has data, when I request an update and submit a file to be updated/replaced, then that file is replaced in the dataset
- [ ] Given a dataset that already has data, when a an update occurs, only the new versions of changed or added metadata results in an increased storage cost.
- [x]  Given a dataset that already has data, when a an update is requested, then validation is rerun.
- [x]  Given a dataset that already has data, when an update fails validation, then the dataset is not updated and the validation errors are returned to the user.
- [x] Given an update has been requested, when it finishes, a SNS message is generated with the results.

#### Additional context

Typical use cases are:

1. updating metadata as we find errors and as upgrades to STAC versions occur. This will happen very frquently and almost immediately from day one with historic imagery
2. A corrupted asset file is found and needs to be updated, probably less frequent
3. Every datatype business group will likely have a different frequency and type of updates, for exampe vector data may have frequent updates to a single asset file, but rarely to the metadata. Probably worth considering flexibility in how we implement this for the future.

#### Tasks

- [ ] ...

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Closing. Has been split into #1051 #1224 #1049 #1050 #1237
