### ISSUE TITLE
Notify when new dataset or version or a failure

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#560]
### User Story

So that I know when my import has finished, as a Data Maintainer, I want a notification when the import has finished, and if it has failed, I'd like to know why.

#### Acceptance Criteria

- [x] Given an existing dataset, when a new version (including the first version) is created, then a notification is created
- [x] Given there are multiple datasets, when I have defined a dataset or datasets I am interested in , then I only receive notifications for that dataset(s)
- [x] Given an import has started, when it fails, then a notification is generated with a useful message that gives me enough information to investigate and resolve the issue

#### Tasks

- [x] Create an SNS topic
- [x] Send message when import is finished or failed 
- [x] send required info which user will use for filtering
- [ ] user documentation on how to subscribe

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Duplicate of another issue about notifications
