### ISSUE TITLE
Support assuming a role in a staging bucket account

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#580]
### User Story

So that I can manage access to my staging bucket more easily, as a Data Maintainer, I want to supply a role arn that gives readonly access to my staging bucket

#### Acceptance Criteria

- [x] Given I have a role arn in my staging bucket with the correct permissions to import data from my staging bucket, when I supply a role arn to the dataset-versions end point, then the role arn is used by the data lake to gain accces to the S3 bucket and import the data
- [x] Given I have a role arn with the incorrect permissions to import data from my staging bucket, when I supply a role arn to the dataset-versions end point, then a suitable message is returned to the user and the new version / import process fails
- [x] Given I haven't yet set up a role in my staging bucket account, when I view the help documentation, I am provided examples or scripts to assist me in setting up the role correctly
- [ ] (impossible to test edge case?) ~~~Given I have a role arn in my staging bucket with the correct permissions to import data from my staging bucket, when the role or permissions are changed part way through an import, then the data import is stopped and a suitable message is logged~~~

#### Tasks

- [x] Implement receiving a role ARN which Geostore will assume to reach the staging bucket.
- [x] Change documentation to explain the role & policy the users will have to set up, **excluding** the ARN of the role they would pass when using *our* staging bucket (this might become a feature later).

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
This looks good. Thanks @l0b0
