### ISSUE TITLE
Manage renaming a dataset

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#611]
### User Story

So that users can find my dataset by browsing with the S3 API, as a Data Analyst, I want to know how I can manage dataset name changes

This shouldn't replace other, richer ways to browse the data, e.g. via STAC files/API.

#### Acceptance Criteria

- [x] Given a dataset has been named incorrectly, when a Data Maintainer wants to rename a dataset, then the Dataset Maintainer knows how to request a dataset name change
- [x] Given a dataset has been named incorrectly, when a Data Maintainer wants to rename a dataset, then the Dataset Maintainer knows the implications of renaming a dataset
- [x] Given a dataset doesn't exist yet, when a Data Maintainer creates a new dataset, then the Data Maintainer understands the importance of choosing a name that will endure and not need changing later

##### Potential problems
-  [x] Renaming URLs will break downstream references
   - see task below, otherwise might be a known issue
- [x] Need to solve naming conflicts e.g.
   - not a problem if we do renaming and lock access while doing it
   - UUIDs in path will solve most issues
- [x] Need to solve how to delete/archive the old 'renamed' directories
   - will be resolved when we need to do this, or glacier 'delete' tag
- [x] Need to solve someone renaming a dataset while adding a new version
   - not a problem if we do renaming and lock access while doing it

#### Tasks

- [x] document in [Confluence](https://confluence.linz.govt.nz/display/LGDL/Dataset+Space+Endpoint) info on naming a dataset
- [x] write some info in the help doc about naming a dataset, with some summary of the implications, how to do it and how to avoid renaming (examples etc?)

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Left some

**Comment by billgeo** [comment]
Left some
