### ISSUE TITLE
Restore previous version of a dataset

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#623]
### User Story

So that I can correct a mistake in a dataset version, as a Data Maintainer, I want to restore a dataset to a previous version by specifying a version ID or datetime 

#### Acceptance Criteria

- [ ] Given a dataset with multiple versions, when I accidentally update a dataset with incorrect data, then I want to restore a previous version of a dataset (this doesn't make much sense)
- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Duplicate of #1051
