### ISSUE TITLE
Commuincate key performance indicators

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#629]
### Enabler

So that we can track how the data lake is performing over time, we want to have some way to get key performance indicator data

#### Acceptance Criteria

- [ ] Anyone in the product team (including the PO) can get the status and history of the key performance indicators
- [ ] Supports the Key Performance indicators described here https://confluence.linz.govt.nz/display/LGDL/Key+Performance+Indicators
- [ ] Can be expanded or altered easily to support other performance indicators in the future

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Will do this with later with Elastic Search
