### ISSUE TITLE
Do first release

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#667]
### User Story

So that I can use the new data lake, as a data maintainer, I want the data lake released

#### Acceptance Criteria

- [ ] Given a logged-in data maintainer, when they submit a request to create a dataset in production, then the dataset is created successfully

#### Tasks

- [x] Follow [release process](https://confluence.linz.govt.nz/display/LGDL/Production+Deployment), create and push release branch
- [x] Verify that the process completes without warnings, or if there are any warnings, they are the same as in [non-prod deployments](https://github.com/linz/geostore/actions/workflows/deploy.yml?query=branch%3Amaster)
- [x] Create and push [release tag](https://github.com/linz/geostore/runs/2741537756?check_suite_focus=true)
- [x] Run [production upgrade test deployment](https://github.com/linz/geostore/runs/2741657550?check_suite_focus=true) to make sure upgrade from current production version works
- [x] Deploy the same commit twice to make sure production upgrades work

#### Definition of Ready

- [x] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by imincik** [comment]
Try to release/deploy on the same commit twice to test if it works.

**Comment by billgeo** [comment]
Looks great. Thanks!
