### ISSUE TITLE
Rename the product

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#670]
### Enabler

So that we have an enduring memorable name that reflects better what the product is, we want to rename it

#### Tasks

- [x] Ideas for names have been collected from a wider group
- [x] Shortlist / priority by team
- [x] Vote from LI and other stakeholders
- [x] Final decision by product owner
- [x] Github repo name changed
- [x] References in code base or infra have been chanegd
- [ ] References in documentation have been changed
- [ ] Reference in Github issues changed?

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
FYI @l0b0

**Comment by billgeo** [comment]
Vote was 11 people to 9 in favour "Geostore" over keep the "Geospatial Data Lake".

**Comment by billgeo** [comment]
Thanks @imincik . I've created another issue to rename in the documentation. So can close this one now.
