### ISSUE TITLE
Spike: test if we can browse by indexing the current DL metadata

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#672]
### Enabler

So that we know if we need to build a full STAC catalog now or not, we want to do some research about browsing the Data lake metadata without a root STAC catalog item.

#### Acceptance Criteria

- [ ] Test if there is anything that can index the metadata without a having a global catalog (timeboxed at a few days)

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
