### ISSUE TITLE
Make copy jobs synchronous

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#673]
### User Story

So that I can know when an import is finished, as a Data Maintainer, I want the overall import process to remain unfinished unto all steps in the import, including copying the data/metadata are finished.

#### Acceptance Criteria

- [ ] Make copy jobs synchronous
- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]

#### Additional context

There is no automatic announcement functionality built into batch jobs. We have at least three options for waiting until the copy jobs have completed before finishing the pipeline:

- [Poll for the result](https://docs.aws.amazon.com/step-functions/latest/dg/sample-project-job-poller.html). This is probably the simplest, as we already have the code to check the current status in the `import_status` endpoint.
- Look for a [completion entry in the logs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/batch-ops-examples-event-bridge-cloud-trail.html). This is probably going to be really costly, since we want to log plenty of things.
- [Wait for an SQS message with a task token](https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html#connect-wait-token). This is very flexible and should be fast, but would require adding at least an SQS queue and appropriate access to write to and read from it.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [x] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
I think I can close this one. No real way for me to test this. But happy to accept it.
