### ISSUE TITLE
Update a dataset catalog with new version

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#674]
### User Story

So that I can browse the versions in the metadata, as a Data Analyst,  I want the 'dataset metadata' updated whenever a new version is created

#### Acceptance Criteria

- [x] Add a dataset catalog when a new dataset is created
- [ ] Update (or regenerate?) the dataset catalog when a new version is added

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Thanks @MitchellPaff. Couple of things...

1. Can you update the USAGE.md with changes to the dataset end point (having to specify a description for example). Should probably indicate that best practice is that this is the same description and title as in the metadata.
2. `"type": "Catalog"` seems to be missing from the catalog.json see https://github.com/radiantearth/stac-spec/blob/master/catalog-spec/catalog-spec.md#catalog-fields
