### ISSUE TITLE
Add root Data Lake catalog metadata

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#675]
### User Story

So that I can browse the datasets in the metadagta, as a Data Analyst, I want a STAC compliant root metadagta catalog for the entire data lake

#### Acceptance Criteria

- [ ] Add a root/global catalog
- [ ] Update global catalog when new dataset is added (or removed)
- [ ] Ensure something sensible happens if two datasets are created at the same time (a queue?)

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [x] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Looks good. But doesn't seem to be v1.0.0-rc.4 compatible. Missing the `"type": "Catalog"` property

**Comment by MitchellPaff** [comment]
seems to have been fixed but only on the beta version which we are currently one version behind. https://github.com/stac-utils/pystac/pull/288/commits/1d2b7c1fda2717768e8ad6297dbd7bdb10eba6a2

**Comment by billgeo** [comment]
Okay. Let's accept this issue and implement it later. I'll add an issue on the backlog.
