### ISSUE TITLE
Remove timestamp from the dataset part of the S3 path

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#703]
### User Story

So that I can read and browse the S3 object key/path easily, as a data analyst or developer, I want the timestamp removed from the 'dataset' part of the path.

#### Acceptance Criteria

- [ ] Given a dataset path in S3, when it is browsed or listed via the S3 API, then the dataset part of the path only contains the dataset title and the UUID and does not contain a system generated timestamp

e.g.

`s3:<bucket>/<dataset-title>-<UUID>/<timestamp>-<UUID>`

not

`s3:<bucket>/<dataset-title>-<timestamp>-<UUID>/<timestamp>-<UUID>`

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Looks good. Thanks @l0b0
