### ISSUE TITLE
Spike: research STAC browsers

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#710]
### Enabler

So that we can POC a STAC brower and/or API, we want to research the options for implementing STAC browsing functionality

User: Data Analyst

See https://github.com/linz/geospatial-data-lake-team/issues/59  for user story/requirements

#### Acceptance Criteria

- [ ] All available options have been investigated for pros and cons, including technology fit, license, cost, user experience, maturity and effort for the product team to incorporate
- [ ] Options presented to the team with recommendations
- [ ] Recommendations presented to key experts in this area (a special demo?) e.g. @palmerj @jacobus etc
- [ ] Team decision on best option to use in the POC

#### Tasks

- [ ] ~~Incorporate @jacobus POC on a bespoke index using AWS services like Elasticsearch etc~~
- [ ] Investigated options in this server list here: https://stacindex.org/ecosystem?category=Server
- [ ] Investigated options in this GUI list here: https://stacindex.org/ecosystem?category=Visualization
- [ ] Could also consider QGIS as an interface, e.g. https://github.com/linz/linz-data-importer
- [ ] Looked in other places?
- [ ] Results written up in confluence
- [ ] Present results to the team
- [ ] Decision made by the team 

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
