### ISSUE TITLE
Spike: research how to support curated groups of datasets

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#711]
### Enabler

So that we can support Data Maintainers who want to group their datasets together in 'curated groups' (e.g. imagery/aerial), we want to research how we can group datasets together for browsing (STAC API/UI and S3 browsing) and searching 

#### Acceptance Criteria

- [ ] The team has a good knowledge of the options to support these user stories
- [ ] The team agrees on the best option to support these user stories

#### Tasks

- [ ] Research common ways to do this using STAC metadata
- [ ] Research common ways to do this using S3 paths
- [ ] Document results and make recommendations
- [ ] Team discussion to decide which option(s) to pick for implementation

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Closing this until needed.
