### ISSUE TITLE
Making logging format consistent for storage and analysis 

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#712]
### User Story

So that I can access information about the system (e.g. with Elasticsearch and Kibana), as a Data Analyst, Developer or Administrator, I want logs prepared consistently to the LINZ standard so they can be sent to LINZ central logging system.

#### Acceptance Criteria

- [x] All relevant info is logged consistently
- [x] Logging message match the LINZ format (specified in Confluence?)

#### Additional context
LINZ Central logging is in undergoing upgrade which will result in logging process and setup simplification. In [Logging documentation](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=83649508), top diagram is showing new state and lower one the old one.

* [aws-log-config](https://github.com/linz/aws-log-config) will be used to configure log shipping. 
* aws-log-config depends on [linzjs/cdk-elastic-shipper](https://github.com/linz/elasticsearch-shipper)
* [ept-central-applogs](https://github.com/linz/ept-central-applogs) is used for deployment of whole LINZ Central Logging solution

In new version of LINZ Centralized Logging all logs from product AWS account should be automatically imported to LINZ Centralized Logging system based on aws-log-config configuration (see [basemaps config](https://github.com/linz/aws-log-config/blob/master/config/basemaps.json) as example).

New LINZ Centralized Logging version is not ready yet (needs few weeks to be finished and to populate aws-log-config with configuration for all products). 

Kibana needs space created, it is not automatic
Slack messages are configured by ElasticSearch configuration (see: https://github.com/linz/basemaps-team/blob/master/config/elasticsearch/watch.aws.AssumeRoleWithSAML.json)

#### Tasks

- [x] Logs (format and content) are consistent with [LINZ best practice](https://confluence.linz.govt.nz/display/GEOD/Logging)
- [ ] Log entries relating to a user request _all_ include the same unique ID enabling the easy tracking of all log entries related to a request.
- [ ] Tests updated

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Closing this and will open new issue to format the message blob into key:values
