### ISSUE TITLE
Add code quality badges

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#718]
### Enabler

To improve user confidence, we want to show which code quality steps we've taken.

#### Acceptance Criteria

- [x] Badges in readme inform users of our main quality assurance steps taken

#### Additional context

There is no official Gitlint/Shellcheck badge yet, so I've created custom ones.

#### Tasks

- [x] Add code coverage metric (either current level or minimum limit) badge to readme
- [x] Add badges for automated code checking tools, including at least Black, Conventional Commits, Gitlint, hadolint, isort, mypy, prettier, pylint and shellcheck

#### Definition of Ready

- [x] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
