### ISSUE TITLE
Rename the product in documentation

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#721]
### User Story

So that I know what the product is called, as a user or stakeholder, I want to see the correct name in all the documentaiton.

#### Acceptance Criteria

- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]
- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]

#### Tasks

- [x] Update confluence
- [x] Update Teams
- [x] Update objective
- [x] Update Psoda
- [x] Update github issues?
- [x] Update Slack

- [x] Update AWS account names and find out if this will break anything

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
I've done everything I can control and have asked Gokul to find out if we can change AWS account names.
