### ISSUE TITLE
Use consistent construct IDs

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#730]
### Enabler

So that constructs end up with legible, similar names, we want to be consistent when setting their IDs.

#### Acceptance Criteria

- [ ] All infrastructure construct IDs use the same, simple format
- [ ] Ideally, the individual words in construct IDs are trivially discernable

#### Additional context

Will spaces, hyphens or underscores in construct IDs be removed from the final construct name? If any of them are not removed, we could use that as a word separator. Another alternative is if "Title Case" is changed into "TitleCase", which would also be legible.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
