### ISSUE TITLE
Get to 100% coverage

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#731]
### Enabler

So that we can have confidence in all our code, we want to achieve 100% test coverage.

This also helps with new code, since anything less than 100% means we could introduce new code paths which are untested.

#### Acceptance Criteria

- [ ] The coverage setting `fail_under` is set to `100`
- [ ] The readme coverage badge says "100%"

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
