### ISSUE TITLE
Upgrade to pystac 1.0.0

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#737]
### Enabler

So that the metadata is consistent (all on stac version 1.0.0) we want to upgrade to pystac 1.0.0 as soon as there is a non-beta version released.

Note: the current version of pystac is stuck on stac spec 1.0.0-beta2, the rest of teh data lake is using the latest version 1.0.0-rc.4 which has breaking changes

#### Acceptance Criteria

- [ ] ...

#### Tasks

- [ ] Upgrade to pystac 1.0.0, which should comply with stac spec 1.0.0-final
- [ ] Consider using pystac for all metadata creation or editing to ensure that the versions are consistent across the data lake

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
