### ISSUE TITLE
Improve metadata description for catalog metadata

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#742]
### User Story

So that I can understand more about the catalog metadata for the Geostore, as an external data analyst or developer, I want a good description and other relevant metadata in the catalog.json files.

#### Acceptance Criteria

- [x] Given the bucket is deployed, when a dataset is created, then the title should read "LINZ Geostore"
- [x] Given the bucket is deployed, when a dataset is created, then the description should read:
`The Geospatial Data Store (Geostore) contains all the important geospatial data and metadata held by Land Information New Zealand (LINZ).<br/>Please browse this catalog to find and access our data.<br/>For more information see: TODO - add URL to help page.`
- [ ] Given a dataset, when a new version is created, the description of the dataset 'catalog.json' should be updated from the collection.json description
- [ ] Given a dataset, when a new version is created, the title in the dataset 'catalog.json' should be updated to the title from the collection.json

#### Additional context

Note: see old data lake root catalog for ideas. See other nicely described catalogs on the web for ideas (AWS Open Data Registry for example).

#### Tasks

- [ ] Possibly want to change dataset endpoint change 'title' to 'directory-name' (or something), update documentation (Confluence as well as Github) as well
- [ ] 

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
