### ISSUE TITLE
Write basic comms plan

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#746]
### Enabler

So that we can keep users and stakeholder informed, we want to write a basic comms plan the identifies a strategy for all of them

#### Acceptance Criteria

- [ ] We have a basic comms plan that makes sure we cover all teh users and stakeholders captured in the customer onion.

#### Additional context

Customer Onion and other user analysis is here: https://confluence.linz.govt.nz/display/LGDL/Customer+Onion

#### Tasks

- [x] Draft a basic comms plan, maybe a simplified version of the [Basemaps one](https://confluence.linz.govt.nz/display/LTS/Comms+Plan%3A+Launch+of+LINZ+basemaps)
- [x] Review with @vlindsay and team
- [x] Make any changes
- [x] create artefacts to do actions (definition of done actions, stories etc)

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Created a template with headings here:

https://confluence.linz.govt.nz/display/LGDL/Comms+Plan

**Comment by billgeo** [comment]
Closing. Well reviewed and followup stories created.
