### ISSUE TITLE
Use program for easy version bumping

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#748]
### Enabler

So that we can bump the version easily, we want to use a third party program to update the relevant files

#### Acceptance Criteria

- [ ] Creating a new version should be as simple as running a single command indicating whether to bump the major, minor or patch version

#### Additional context

See for example [bump2version](https://github.com/c4urself/bump2version), also [suggested for the template repo](https://github.com/linz/template-python-hello-world/issues/4).

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
