### ISSUE TITLE
Incident management process

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#749]
### User Story

So that I can contact support and know that the system is well supported, operated and maintained, as a data analyst or developer, I want to easily contact support and resolve any issues.

#### Acceptance Criteria

- [x] Given a user of the geostore, when support incident happens, then they know who to contact and can do that easily (e.g. support / error hints in the lambda funciton / ui / cli etc)
- [x] Given a user of the geostore, when a support incident happens, if I contact service desk the product team is contacted as soon as possible
- [x] Given a user of the geostore, when a support incident happens that is not related to the geostore, if I contact service desk then the geostore product team is not contacted

#### Tasks

- [x] Check documentation for similar systems - Basemaps / LDS Data Staging / LDS / other IT systems etc
- [x] Update and/or move existing documentaton - https://confluence.linz.govt.nz/display/LGDL/High+Level+Design#HighLevelDesign-Support,Operations&Maintenance
- [x] Discuss with Open Data about tier 2 support
- [x] Do operational readiness form / checklist
- [x] team review

#### Definition of Ready

- [x] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Hi @JoCaudwell just wondering if you would have time to start on this task? 

> Do operational readiness form / checklist

I'll do the first three tasks.

**Comment by JoCaudwell** [comment]
Hey @billgeo , I'll try to have a look at it tomorrow

**Comment by JoCaudwell** [comment]
Draft Service Desk Knowledge Article is here: https://confluence.linz.govt.nz/display/LGDL/Geostore+KCS+Knowledge+Article

Meeting set up with Dave (Datacom SDM) from the service desk on 18/07. 

@billgeo to confirm resolver group (LINZ Data Services) and confirm the email mapsatLINZ@linz.govt.nz)
