### ISSUE TITLE
Validate the 'LINZ' top-level metadata extension 

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#78]
So that I can ensure my metadata has all the LINZ required metadata elements, as Data Maintainer, I want to validate the LINZ top-level metadata extension 

[LINZ metadata extension profile](https://github.com/linz/STAC)

#### Acceptance Criteria

- [x] LINZ top-level extension is validated as a 'required' (mandatory) extension
- [x] If the LINZ top-level extension is missing then an error is returned to the user and import is aborted
- [x] Validation errors are returned to the user
- [ ] Validation rules are well-tested including negative tests (in the source STAC json schema repo?)

#### Tasks

- [x] Add LINZ STAC spec schema to Geostore validation
- [x] Make sure 'user friendly' error messages are returned to the user
