### ISSUE TITLE
Change management process

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#782]
### Enabler

So that we have a well-design change management provcess that aligns as much as possile with LINZ and/or STEP, we want to understand LINZ and STEP change management and document how it will work for the Geostore product team and users.

#### Acceptance Criteria

- [ ] Change management at LINZ is well understood
- [ ] We have a simple, effective change management process is aligns with LINZ and works for the team and the users

#### Tasks

- [ ] write a  change management process that works for us
- [ ] talk to new LINZ change manager person
- [ ] find STEP change processes (tiered changes etc)
- [ ] team review

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Closing, we have an adequate CI and deployment process.
