### ISSUE TITLE
Easily update collection metadata

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#789]
### User Story

So that I can update my metadata frequently and easily, as a Data Maintainer (Historic Imagery), I want to update the metadata by only supplying the metadata I want to update and not supplying the assets.

#### Acceptance Criteria

- [ ] Given an existing dataset, when I want to update only the metadata files (no assets), then I can submit metadata referring to assets that already exist in a geostore version.
 
#### Tasks

- [ ] Add functionality to allow copying assets from the geostore's own bucket with metadata that is in a different bucket
- [ ] Might need to extend the roles
- [ ] Limit it to supplying only one role to manage all buckets
- [ ] Could do this with existing functionality? just add example to documentation somewhere?
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by l0b0** [comment]
How would "only dataset metadata is supplied" be implemented? Rather than trying to second guess what the user is trying to do, I would suggest we document how to update the metadata and leave it to the user to use the right approach.

**Comment by l0b0** [comment]
I assume you mean "assets" and not "assets or file", since the only other files are metadata.

**Comment by l0b0** [comment]
"[W]hen I update my dataset metadata and don't update any assets or file, then a new version is not created" is risky:

- Reverting to an earlier version would be harder, because we would have two different notions of "version" - actual dataset versions and metadata file versions.
- We would have to do some different validation of the new metadata to ensure that it has been as thoroughly validated as the original metadata. We'd at least have to assert that the asset URLs and checksums are all the same as in the original.

**Comment by billgeo** [comment]
No longer needed. This is covereed by #559
