### ISSUE TITLE
Improve logging for LINZ Centralized Logging integration

### ISSUE THREAD

**Issue by imincik** [linz/geostore#819]
### Enabler

So that Geostore is prepared for LINZ Centralized Logging integration, we want to improve logging messages according its requirements.

#### Acceptance Criteria

- [ ] Correlation ID is added to all logging messages
- [ ] ...

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Duplicate
