### ISSUE TITLE
Support Topo Processor Team to test first upload

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#821]
### User Story

So that I can easily develop a process that uses the Geostore, as a developer, I want a Geostore product team developer to sit with me and help me test and develop my process.

note: this will also help the geostore team to understand better how the product is being used

#### Acceptance Criteria

- [x] One dataset is successfully tested in non-prod

#### Tasks

- [x] Attend Topo Processor Planning Session
- [x] Confirm Topo Processor can access non-prod/ set up access
- [x] Help Topo Processor team

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by l0b0** [comment]
Resulted in https://github.com/linz/geostore/issues/890 and https://github.com/linz/geostore/issues/892.
