### ISSUE TITLE
Add key missing metadata to LINZ STAC extension

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#826]
### Enabler

So that we can validate the key LINZ STAC properties, we want to add key LINZ metadata properties to the LINZ extension.

#### Acceptance Criteria

- [x] Following rules added to the extension:
   - [x] 'security_classification' property (Enumeration - see levels [here](https://www.digital.govt.nz/standards-and-guidance/governance/managing-online-channels/security-and-privacy-for-websites/foundations/classify-information/) for values) - add and make mandatory
   - [x] Make the ['version' community extension](https://github.com/stac-extensions/version) mandatory for all datasets
   - [x] Make the 'quality' extension mandatory for all datasets see #843
   - [ ] ~~Make the 'providers' property (see stac spec core) mandatory for all datasets~~
   - [ ] ~~Make these two 'providers' 'roles' mandatory 'licensor' and 'producer', other roles are optional.~~

#### Additional context

See [new metadata analysis](https://confluence.linz.govt.nz/display/LIFFP/STAC+Field+Mapping). We can probably [combine](https://json-schema.org/understanding-json-schema/reference/combining.html) our rules with the STAC JSON schema easily.

#### Tasks

- [ ] 
- [x] Add tests
- [x] Update README
- [x] Update JSON Schema

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
FYI @palmerj @dwsilk

**Comment by billgeo** [comment]
@l0b0 would you have time to edit the acceptance criteria for this one and add an estimate before planing this afternoon?

**Comment by billgeo** [comment]
Needs to be estimated at refinement today.

**Comment by l0b0** [comment]
We might've already discussed this, but I think the `security_classification` property should be part of a separate extension, since it isn't completely LINZ-specific. This issue would then be about making it mandatory.

**Comment by billgeo** [comment]
In the discussion, which we recorded in the confluence page, we decided to leave it in the LINZ extension for now as we weren't sure anyone else would want to use it and to keep it relatively simple for now.

I don't think many (any?) of these things will be completely LINZ specific more just a collection of things that are useful for LINZ. Could we take this approach now and move it to a separate extension later? Or would that be problematic?
