### ISSUE TITLE
Spike: clarify LINZ STAC mapping / profile

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#827]
### Enabler

So that we can start implementing a LINZ STAC profie, we want to clarify some of the mapping and decide the likely path to implement it (e.g. use/extend an existing community extension or create a new community extension)

#### Acceptance Criteria

- [x] We have enough information to start implementing the LINZ Profile(s)
- [x] We should look to reuse existing extensions where possible
- [x] New extensions we create should be logically named and purposeful
- [x] Where possible we should avoid a 'linz' extension so that other in the community can adopt it and help maintain

#### Tasks

- [x] Update confluence spreadsheet 'path to implementation' column where it is obvious 
- [x] Discuss remaining items with @dwsilk @palmerj @jacobus and agree on a reasonable path forward, noting that we can always change it later

#### Definition of Ready

- [x] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
I'm capturing some initial thoughts to be reviewed and extended by @l0b0. Workshop on Friday with key people to finalise it.

**Comment by billgeo** [comment]
i think we've done about all we can on the confluence page. Will try and resolving outstanding questions in workshop on Friday.

**Comment by billgeo** [comment]
Both workshops completed (thanks @l0b0 for taking the second one). We have plenty of info to get started and the rest can be tested as we implement them. Closing....
