### ISSUE TITLE
Kibana POC: Collect test metadata 

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#829]
### Enabler

So that we can have an effective Kibana POC, we want to get or create some test datasets/metadata they helps user provide good feedback

#### Acceptance Criteria

- [x] We have metadata for at least 10 datasets, ideally 50+
- [x] There are datasets from different areas of NZ
- [x] We have some datasets with overlapping geographies (e.g. two datasets in the Wlg region)
- [x] We have datasets of different domains (e.g. aerial imagery, topo vector data, liDAR)
- [x] We have multiple versions for some datasets
- [x] The test data is small and portable (empty asset files etc)
- [ ] The test data is in an S3 bucket

#### Tasks

- [x] Get LDS metadata
- [x] Write XSLT convertor
- [x] Convert LDS ISO metadata to STAC for testing
- [ ] Add some test metadata elements to highlight likely metadata we will search on later, e.g. group = "Aerial Imagery", content_type = "Polygon", geographic_description = ["New Zealand", "Wellington"]
- [x] Link to test file
- [x] Put it all in the non prod staging/ Geostore S3 bucket in one of our test accounts or a sandbox account.

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [x] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Closing this. Meets all the accpetance criteria,. We might want to fudge a bit more metadata next week for the workshop. But will do that as needed.
