### ISSUE TITLE
Kibana POC: Setup elasticsearch and kibana

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#830]
### User Story

So that I can use Kibana, as a developer or data analyst (POC users), I want elastic search set up with quality test data and my access to everything configured.

#### Acceptance Criteria

- [x] Test metadata is imported to elastic search
- [x] Metadata elements are mapped to data types etc correctly 
- [x] All metadata is indexed
- [ ] Test users have access to Elasticsearch/Kibana
- [x] We undertstand how we will give access to all of LINZ

#### Tasks

- [x] use Blayne's script to input data to elastic
- [x] Create elastic search indexes / modify template mapping in blayne's script
- [x] add test users + Geostore team to kibana user group 
- [x] Can everyone at LINZ get access? Confirm with Terence? 
- [x] Add tasks about giving access to all of LINZ to 'productionise' user story

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Hi @MitchellPaff, I'm happy to close this as soon as we have access for me and the workshop users.
