### ISSUE TITLE
In-depth demo

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#848]
### User Story

So that I can get a good understanding of the new Geostore functionality, as a LINZ Data Maintainer or Data Analyst, I want an in-depth demo to show me how to use the product and get started.

#### Acceptance Criteria

- [ ] Given , when [an event happens], then [an expected outcome occurs]
- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]

#### Tasks

- [ ] Prepare in-depth demo
- [ ] Run in-depth demo
- [ ] Record feedback where appropriate - e.g. new stories

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
