### ISSUE TITLE
Create a LINZ 'top-level' STAC metadata extension

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#850]
### Enabler Story

So that we can specify which metadata extensions LINZ needs and which properties are mandatory, we want an initial LINZ top-level STAC metadata extension (README, json schema etc) that validates a simple property, e.g. `title`

Top-level is an overarching metadata extension that manages the other 3rd party extensions that LINZ uses, including setting properties to mandatory that are otherwise optional.

#### Acceptance Criteria

- [x] Given a collection that validates against this extension, when the `title` property is missing, then validation fails.
- [x] Given a collection that validates against this extension, when the `title` property is present but contains an empty string, then validation fails.
- [x] Given a collection that validates against this extension, when the `title` property is present and contains any string, then validation passes.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Happy with the demo you did for this. So can close it as soon as it's merged.

**Comment by billgeo** [comment]
> I am not sure if I understand Acceptance Criteria correctly. Do we want to make `title` or `linz:title` property mandatory ?

Sorry missed this @imincik . I only get notified of a comment if I'm mentioned directly. :)

Looks like you picked the right one anyway.
