### ISSUE TITLE
Investigate Dependabot not updating some packages

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#878]
### Enabler

So that packages are being updated reliably, we want to check that Dependabot is working as expected.

#### Acceptance Criteria

- [ ] No inexplicable [version upgrade](https://github.com/linz/template-python-hello-world/network/updates) failures, in particular Dependabot should generate package update PRs for all packages updated with `poetry update`.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
