### ISSUE TITLE
Work out uniqueness constraints of metadata IDs

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#885]
### Enabler

So that the meaning of IDs can be well documented and verified, we want to establish rules for their uniqueness.

#### Acceptance Criteria

- [ ] There should be clear documentation available in the repository explaining which IDs have to be distinct from which other, when (if at any time) the uniqueness constraints can be relaxed, and how to generate unique IDs easily.
- [ ] The dataset validation process should include a step which verifies that uniqueness constraints are upheld.

#### Additional context

This is in response to discussions around IDs as useful indicators of uniqueness. For example, for IDs to be useful at all they need to uniquely identify some data. So it should be unsurprising that an Item ID should change when the associated asset file contents change. What may be more interesting is that every ancestor (via `"rel": "parent"`) metadata file *recursively* should get a new ID in the same situation. This ensures that the ancestor IDs are all unique if and only if any of their descendants have changed. This allows a dataset user to simply compare two top level IDs to verify that two copies of a dataset are different, and allows them to detect *which parts* of a dataset have changed by following the changed IDs down to the child metadata.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
