### ISSUE TITLE
Propose a new extension to STAC community

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#886]
### Enabler

So that our extensions are supported by a larger community, we want to propose our most general purpose extensions as community extensions and understand any further work they may need to make them accepted by the community.

https://stac-extensions.github.io/#adding-a-new-extension

See #967 for initial ideas to propose

#### Acceptance Criteria

- [ ] Discussion with STAC community is productive and respectful
- [ ] Results recorded in somewhere (probably in a LINZ Metadata area in confluence).
- [ ] We have a good understanding of what is of interest to the community
- [ ] We have a good understanding of any further work to make the extensions adopted by the community
- [ ] Followup stories added to the backlog
- [ ] Any draft PRs that are waiting on community feedback are merged or discarded as appropriate

#### Tasks

- [ ] Ask for initial feedback in an issue or the discussion GH feature
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Done
