### ISSUE TITLE
Spike: what are STAC IDs for?

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#887]
### Enabler

So that we know if we need to validate STAC IDs (duplicates etc), we want to understand what IDs are for in the LINZ context; what will we use them for, what will external users use them for?

#### Acceptance Criteria

- [ ] We understand if we the Geostore system will use the IDs for anything
- [ ] We understand if the data maintainers will use the IDs for anything
- [ ] We understand if end users (internal and external) will use the IDs for anything

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
