### ISSUE TITLE
Spike: discuss design for cost effective updates of existing datasets

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#888]
### Enabler

So that we can create tasks for #559, we want to design a good solution that has minimal tradeoffs and maximal flexibility for future stories (See non-functionals [here](https://github.com/linz/geostore/blob/master/.github/ISSUE_TEMPLATE/user_story.md))

Note: for the non-functional on cost. The cost per GB of data includes previous revisions. So as revisions increase the cost should stay under that threshold.

Typical scenarios that we know will likely break this threshold are: 

-     updating metadata as we find errors and as upgrades to STAC versions occur. This will happen very frequently and almost immediately from day one with historic imagery
-     A corrupted asset file is found and needs to be updated, probably less frequent
-     Every datatype business group will likely have a different frequency and type of updates, for example vector data may have frequent updates to a single asset file, but rarely to the metadata. Probably worth considering flexibility in how we implement this for the future.

#### Acceptance Criteria

- [x] We have a plan forward / high level design

#### Tasks

- [x] 1 hr design/whiteboard discussion
- [x] if needed, another 1 hr discussion
- [x] document design changes/decisions in confluence
- [ ] update #559 with design, tasks and estimates
- [x] Organise workshop with Daniel, Jack and Geostore Team
- [x] Do workshop/research/thinking etc
- [x] Document results

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
