### ISSUE TITLE
Use boto3 standard retry mode

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#893]
### Enabler

So that retrying actions in AWS is more robust, we want to use the standard rather than the legacy (default) [retry mode](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html).

#### Acceptance Criteria

- [ ] All boto3 clients in production code are created with standard retry mode

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
