### ISSUE TITLE
Add STAC extensions for lineage, lifecycle and manager and custodian

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#967]
### User Story

So that I can ensure all the LINZ required metadata is attached to my data, as a Data Maintainer, I want my metadata validated against a 'linz:providers' prioperty, a 'quality:lineage' property and a 'linz:lifecycle' property.

#### Acceptance Criteria

- [x] create a mandatory linz:providers property that is identical to the 'providers' in [stac-spec core definition](https://github.com/radiantearth/stac-spec/blob/789e90fba4c7119bc925d26f75f47bacf44c91e6/collection-spec/json-schema/collection.json#L71-L107) but with the `roles` being an enumeration of `manager` and `custodian`. STAC people suggested doing this another way? Do we know how to do this?
- [x] Add 'quality:lineage' property (Text) to quality extenstion and make mandatory
- [x] Add  'linz:lifecycle' property (Enumeration "under development", "preview", "on going", "completed", "deprecated") - add and make mandatory

#### Additional context

See [new metadata analysis](https://confluence.linz.govt.nz/display/LIFFP/STAC+Field+Mapping). We can probably [combine](https://json-schema.org/understanding-json-schema/reference/combining.html) our rules with the STAC JSON schema easily.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on
  - [ ] Independent (story is independent of all other tasks)
  - [ ] Negotiable (team can decide how to design and implement)
  - [ ] Valuable (from a user perspective)
  - [ ] Estimate value applied (agreed by team)
  - [ ] Small (so as to fit within an iteration)
  - [ ] Testable (in principle, even if there isn't a test for it yet)
  - [ ] Environments are ready to meet definition of done
  - [ ] Resources required to implement will be ready
  - [ ] Everyone understands and agrees with the tasks to complete the story
  - [ ] Release value (e.g. Iteration 3) applied
  - [ ] Sprint value (e.g. Aug 1 - Aug 15) applied

#### Definition of Done

- [ ] This story is **done**:
  - [ ] Acceptance criteria completed
  - [ ] Automated tests are passing
  - [ ] Code is peer reviewed and pushed to master
  - [ ] Deployed successfully to test environment
  - [ ] Checked against [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
  - [ ] Relevant new tasks are added to backlog and communicated to the team
  - [ ] Important decisions recorded in the issue ticket
  - [ ] Readme/Changelog/Diagrams are updated
  - [ ] Product Owner has approved acceptance criteria as complete
  - [ ] Meets non-functional requirements:
    - [ ] Scalability (data): Can scale to 300TB of data and 100,000,000 files and ability to
          increase 10% every year
    - [ ] Scability (users): Can scale to 100 concurrent users
    - [ ] Cost: Data can be stored at < 0.5 NZD per GB per year
    - [ ] Performance: A large dataset (500 GB and 50,000 files - e.g. Akl aerial imagery) can be
          validated, imported and stored within 24 hours
    - [ ] Accessibility: Can be used from LINZ networks and the public internet
    - [ ] Availability: System available 24 hours a day and 7 days a week, this does not include
          maintenance windows < 4 hours and does not include operational support
    - [ ] Recoverability: RPO of fully imported datasets < 4 hours, RTO of a single 3 TB dataset <
          12 hours

**Comment by billgeo** [comment]
@MitchellPaff as discussed, can you see if you can make it mandatory to always have two provider objects for all metadata, one of each role type, i.e. one `manager`and one `custodian`.

**Comment by billgeo** [comment]
Looks good. Thanks @MitchellPaff
