### ISSUE TITLE
Add created and updated dates to LINZ mandatory metadata

### ISSUE THREAD

**Issue by billgeo** [linz/geostore#978]
### User Story

So that ensure that all metadata has a created and a last updated date, as a data manager, I want all metadata to have created and updated datetimes.

#### Acceptance Criteria

- [x] Make [`created`, `updated`, `start_datetime`  and  `end_datetime`](https://github.com/radiantearth/stac-spec/blob/f81324f712a608d4a319fd0a8738193a43ef1d51/item-spec/common-metadata.md#date-and-time) objects mandatory for collections
- [x] Given one of these properties is missing, when metdata is imported, then an validation error and message to user occurs
- [x] Given am invalid datetime string, when metadata is imported, then an validation error and message to user occurs

#### Tasks

- [ ] Add to README in linz extension
- [ ] Add to json schema in linz extension
- [ ] Add to changelog
- [ ] Add to examples/tests

#### Definition of Ready

- [ ] This story is **ready** to work on
  - [ ] Independent (story is independent of all other tasks)
  - [ ] Negotiable (team can decide how to design and implement)
  - [ ] Valuable (from a user perspective)
  - [ ] Estimate value applied (agreed by team)
  - [ ] Small (so as to fit within an iteration)
  - [ ] Testable (in principle, even if there isn't a test for it yet)
  - [ ] Environments are ready to meet definition of done
  - [ ] Resources required to implement will be ready
  - [ ] Everyone understands and agrees with the tasks to complete the story
  - [ ] Release value (e.g. Iteration 3) applied
  - [ ] Sprint value (e.g. Aug 1 - Aug 15) applied

#### Definition of Done

- [ ] This story is **done**:
  - [x] Acceptance criteria completed
  - [x] Automated tests are passing
  - [x] Code is peer reviewed and pushed to master
  - [x] Deployed successfully to test environment
  - [x] Checked against [CODING guidelines](https://github.com/linz/geostore/blob/master/CODING.md)
  - [x] Relevant new tasks are added to backlog and communicated to the team
  - [x] Important decisions recorded in the issue ticket
  - [x] Readme/Changelog/Diagrams are updated
  - [x] Product Owner has approved acceptance criteria as complete
  - [x] Meets non-functional requirements:
    - [x] Scalability (data): Can scale to 300TB of data and 100,000,000 files and ability to
          increase 10% every year
    - [x] Scability (users): Can scale to 100 concurrent users
    - [x] Cost: Data can be stored at < 0.5 NZD per GB per year
    - [x] Performance: A large dataset (500 GB and 50,000 files - e.g. Akl aerial imagery) can be
          validated, imported and stored within 24 hours
    - [x] Accessibility: Can be used from LINZ networks and the public internet
    - [x] Availability: System available 24 hours a day and 7 days a week, this does not include
          maintenance windows < 4 hours and does not include operational support
    - [x] Recoverability: RPO of fully imported datasets < 4 hours, RTO of a single 3 TB dataset <
          12 hours

**Comment by billgeo** [comment]
Hey @MitchellPaff just clarified with @dwsilk . We don't need to make start_time and end_time mandatory. That metadata is covered elsewhere. So you only need to do created and updated. Sorry for getting it wrong.

**Comment by billgeo** [comment]
Thanks @MitchellPaff . Looks good. Closing.

**Comment by billgeo** [comment]
Actually, could you make the schema validation exactly the same as the stac core spec for items for datetimes? So if we do propose it as an extenstion to core it will be the same as what they currently have.

https://github.com/radiantearth/stac-spec/blob/789e90fba4c7119bc925d26f75f47bacf44c91e6/item-spec/json-schema/datetime.json#L40-L51

**Comment by billgeo** [comment]
Sorry adding one more late change. 
After a discussion yesterday on Slack, it sounds like we should use a prefix of all metadata elements.

e.g. `linz:created`, `linz:updated`

https://github.com/linz/stac/blob/34151f0baf5554a05cc621974a8ee90f70b9193f/extensions/linz/schema.json#L18

**Comment by billgeo** [comment]
Looks good. Thanks @MitchellPaff .
